### ISSUE TITLE
Player is unavailable

### ISSUE THREAD

**Issue by oneness0** [YXL76/cloudmusic-vscode#1]
![image](https://user-images.githubusercontent.com/25880389/86873149-54871d80-c110-11ea-9027-3fe01197ba49.png)
![image](https://user-images.githubusercontent.com/25880389/86873166-6072df80-c110-11ea-859c-48afcdbf77d7.png)
为什么配置了mpv路径还会报不存在?

**Comment by YXL76** [comment]
> ![image](https://user-images.githubusercontent.com/25880389/86873149-54871d80-c110-11ea-9027-3fe01197ba49.png)
> ![image](https://user-images.githubusercontent.com/25880389/86873166-6072df80-c110-11ea-859c-48afcdbf77d7.png)
> 为什么配置了mpv路径还会报不存在?

请你完成以下步骤：
1. 将填写的路径输入`cmd`，检查是否能打开`mpv`
2. 确认路径无误后重启`VS Code`，再次查看是否能播放

如果还是不能播放，请告诉我你的`mpv`版本。如果可以的话，可以尝试一下`vlc`是否也有此问题

**Comment by oneness0** [comment]
> > ![image](https://user-images.githubusercontent.com/25880389/86873149-54871d80-c110-11ea-9027-3fe01197ba49.png)
> > ![image](https://user-images.githubusercontent.com/25880389/86873166-6072df80-c110-11ea-859c-48afcdbf77d7.png)
> > 为什么配置了mpv路径还会报不存在?
> 
> 请你完成以下步骤：
> 
> 1. 在`cmd`中输入你填写的路径，检查是否能打开`mpv`
> 2. 确认路径无误后重启`VS Code`，再次查看是否能播放
> 
> 如果还是不能播放，请告诉我你的`mpv`版本。如果可以的话，可以尝试一下`vlc`是否也有此问题

mpv 0.32.0-572-g8fbc4b1737 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Jul  5 08:56:26 +08 2020
FFmpeg library versions:
   libavutil       56.55.100
   libavcodec      58.94.100
   libavformat     58.48.100
   libswscale      5.8.100
   libavfilter     7.86.100
   libswresample   3.8.100
FFmpeg version: git-2020-07-04-04e06beb0

1.cmd中能打开mpv
2.稍后我试试vlc

**Comment by oneness0** [comment]
vlc可以

**Comment by YXL76** [comment]
> vlc可以

我在三台电脑上都无法复现，所以我写了一个代码片段，如果可以的话，请你帮忙测试返回是否为`true`。以此来确定是否是上游的问题。

先安装[command-exists](https://github.com/mathisonian/command-exists)

``` javascript
const commandExistsSync = require("command-exists").sync;

const mpvPath = "path/to/mpv";

console.log(commandExistsSync(mpvPath || "mpv"));
```

**Comment by oneness0** [comment]
> > vlc可以
> 
> 我在三台电脑上都无法复现，所以我写了一个代码片段，如果可以的话，请你帮忙测试返回是否为`true`。以此来确定是否是上游的问题。
> 
> 先安装[command-exists](https://github.com/mathisonian/command-exists)
> 
> ```js
> const commandExistsSync = require("command-exists").sync;
> 
> const mpvPath = "path/to/mpv";
> 
> console.log(commandExistsSync(mpvPath || "mpv"));
> ```

![image](https://user-images.githubusercontent.com/25880389/86899954-40a5e080-c13d-11ea-8021-ca797a79ad97.png)

**Comment by YXL76** [comment]
好的。不过目前我对该BUG的原因还没有任何想法

**Comment by oneness0** [comment]
就这样吧, 不知为何现在我再切换到mpv, 不会报Player is unavailable了, 但就是不能播放, 点播放没反应

**Comment by YXL76** [comment]
那应该就没问题了，`mpv`部分版本不能播放是上游的问题，我也在等更新，现阶段还是用`vlc`比较好
