### ISSUE TITLE
没有看到账号图标？

### ISSUE THREAD

**Issue by chenruifu** [YXL76/cloudmusic-vscode#10]
![image](https://user-images.githubusercontent.com/19771516/88450021-36464f00-ce7e-11ea-9050-0e01c0fc0f53.png)

系统MAC 10.15.6

![image](https://user-images.githubusercontent.com/19771516/88450079-e0be7200-ce7e-11ea-8837-295e3d4ddf16.png)

**Comment by YXL76** [comment]
应该是激活失败，请检查`Help->Toggle Developer Tools->Console`中是否有错误信息。

或者执行命令`Cloudmusic: Sign in`登陆帐号。 @chenruifu

**Comment by chenruifu** [comment]
![image](https://user-images.githubusercontent.com/19771516/88453354-ba0d3500-ce98-11ea-848b-47f7cb12e831.png)

**Comment by YXL76** [comment]
同#5

**Comment by YXL76** [comment]
请更新至`3.4.0`，检查插件是否可用。 @chenruifu

**Comment by chenruifu** [comment]
升级后可以正常登陆，可以获取到收藏列表，但是不能播放

**Comment by YXL76** [comment]
请问`VS Code`是最新版吗？ @chenruifu

**Comment by chenruifu** [comment]
![image](https://user-images.githubusercontent.com/19771516/88872335-82add800-d24c-11ea-8638-b4374c2daf68.png)

**Comment by YXL76** [comment]
请检查`v3.7.4` @chenruifu

**Comment by chenruifu** [comment]
可以的，也能正常播放。
但是会有个问题，我是mac+airpods
![image](https://user-images.githubusercontent.com/19771516/89964468-c953f700-dc7c-11ea-949c-9454e406e87c.png)

1、听久了会卡碟（应该不是网络问题）
2、耳机摘下来不会自动暂停，是切换到内置扬声器（APP是自动暂停的）
3、重新连接声音是从内置扬声器出来的，同个环境APP是从耳机出来的

以上可能是我的个例，给你的这个插件点个赞，开发不容易。

**Comment by YXL76** [comment]
感谢支持。
请问卡碟是指播放自动停止，还是显示正在播放而没有声音，期间是否有错误信息。@chenruifu

**Comment by chenruifu** [comment]
卡碟，就是声音串杂再一起（暂停后再播放又正常，也试了用其他音乐软件打开声音是正常的。没有错误信息的）

**Comment by chenruifu** [comment]
刚电脑重启后，试了几首。貌似卡碟的问题没再重现了。我再多使用以下看，有问题我再反馈...

**Comment by YXL76** [comment]
好的
