### ISSUE TITLE
关于增加快捷键的建议

### ISSUE THREAD

**Issue by LazyCat-xiao** [YXL76/cloudmusic-vscode#135]
能不能给播放控制增加快捷键，例如上下一曲和播放暂停 可以方便的切歌

**Comment by YXL76** [comment]
`vscode`本来就可以设置快捷键，你打开快捷键设置，查找`cloudmusic`相关的命令进行设置 @LazyCat-xiao

**Comment by LazyCat-xiao** [comment]
原来如此，不过音量控制能改下吗，这种改数值的方式并不是很方便

**Comment by YXL76** [comment]
好的，下个版本加上
