### ISSUE TITLE
一直登录失败

### ISSUE THREAD

**Issue by Misakimmmm** [YXL76/cloudmusic-vscode#143]
**两种方式都登录不上去，确定账号密码没有错误并且在网易云网页版里是可以登录的，控制台除了登陆失败没有其他的错误信息输出**

**vscode版本：**
版本: 1.50.1 (user setup)
提交: d2e414d9e4239a252d1ab117bd7067f125afd80a
日期: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Misakimmmm** [comment]
我自己防火墙的问题

**Comment by YXL76** [comment]
> 我自己防火墙的问题

能说说具体是怎么解决的吗？
