### ISSUE TITLE
播放时会卡住，一直显示歌曲加载中

### ISSUE THREAD

**Issue by Misakimmmm** [YXL76/cloudmusic-vscode#148]
![image](https://user-images.githubusercontent.com/64182473/98622972-ad2c2880-2345-11eb-94e8-05af4e027c92.png)
如上图显示的这样，点击播放会卡住，状态栏一直都是这样加载中，点什么都没用，只有重启vscode才行

vscode版本：
版本: 1.51.0 (user setup)
提交: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
日期: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by YXL76** [comment]
这是播放逻辑上的错误，之前在 #35 也有人提到。我下次找个时间修复一下，最近期中考试期间，比较忙。
