### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by a552422934** [YXL76/cloudmusic-vscode#160]
https://share.mubu.com/doc/273_3gJoVK7

**Comment by YXL76** [comment]
1. 已有显示歌词的功能，请手动开启。
2. 推荐的内容非常多，很难决定应该把什么放在`TreeView`里，所以只显示用户个人的内容（后续还会加入电台），其他内容则放在`QuickPick`里，后续还会考虑使用`WebView`

**Comment by YXL76** [comment]
> https://share.mubu.com/doc/273_3gJoVK7

1. 已有显示歌词的功能，请手动开启。
2. 推荐的内容非常多，很难决定应该把什么放在`TreeView`里，所以只显示用户个人的内容（后续还会加入电台），其他内容则放在`QuickPick`里，后续还会考虑使用`WebView`

**Comment by a552422934** [comment]
显示歌词的功能在哪开启，能不能告知一下，没有找到；
推荐歌单只把前10个歌单，放进去就可以了啊；我每天必听的歌单只有“每日歌曲推荐”






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YXL76/cloudmusic-vscode"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月20日(星期五) 下午5:42
收件人:&nbsp;"YXL76/cloudmusic-vscode"<cloudmusic-vscode@noreply.github.com&gt;;
抄送:&nbsp;"张"<552422934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 建议 (#160)





  
https://share.mubu.com/doc/273_3gJoVK7
   
已有显示歌词的功能，请手动开启。
 
推荐的内容非常多，很难决定应该把什么放在TreeView里，所以只显示用户个人的内容（后续还会加入电台），其他内容则放在QuickPick里，后续还会考虑使用WebView

**Comment by YXL76** [comment]
> 显示歌词的功能在哪开启，能不能告知一下，没有找到； 推荐歌单只把前10个歌单，放进去就可以了啊；我每天必听的歌单只有“每日歌曲推荐”
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YXL76/cloudmusic-vscode" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月20日(星期五) 下午5:42 收件人:&nbsp;"YXL76/cloudmusic-vscode"<cloudmusic-vscode@noreply.github.com&gt;; 抄送:&nbsp;"张"<552422934@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 建议 (#160) https://share.mubu.com/doc/273_3gJoVK7 已有显示歌词的功能，请手动开启。 推荐的内容非常多，很难决定应该把什么放在TreeView里，所以只显示用户个人的内容（后续还会加入电台），其他内容则放在QuickPick里，后续还会考虑使用WebView — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

1. 请查看`Pinned issues`
2. 如果你只用“每日歌曲推荐”我就必须把它放到`TreeView`，那么为了照顾所有用户，我是不是应该把所有内容都铺开

**Comment by YXL76** [comment]
`TreeView`的内容只尽可能贴近移动端“我的”页面

**Comment by a552422934** [comment]
显示歌词的功能什么时候添加到说明文档里啊，Pinned issues里好难发现‘
”每日歌曲推荐’默认不展开也行啊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YXL76/cloudmusic-vscode"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月21日(星期六) 上午9:39
收件人:&nbsp;"YXL76/cloudmusic-vscode"<cloudmusic-vscode@noreply.github.com&gt;;
抄送:&nbsp;"张"<552422934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 建议 (#160)





  
显示歌词的功能在哪开启，能不能告知一下，没有找到； 推荐歌单只把前10个歌单，放进去就可以了啊；我每天必听的歌单只有“每日歌曲推荐”
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YXL76/cloudmusic-vscode" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月20日(星期五) 下午5:42 收件人:&nbsp;"YXL76/cloudmusic-vscode"<cloudmusic-vscode@noreply.github.com&gt;; 抄送:&nbsp;"张"<552422934@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 建议 (#160) https://share.mubu.com/doc/273_3gJoVK7 已有显示歌词的功能，请手动开启。 推荐的内容非常多，很难决定应该把什么放在TreeView里，所以只显示用户个人的内容（后续还会加入电台），其他内容则放在QuickPick里，后续还会考虑使用WebView — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
   
请查看Pinned issues
 
如果你只用“每日歌曲推荐”我就必须把它放到TreeView，那么为了照顾所有用户，我是不是应该把所有内容都铺开

**Comment by YXL76** [comment]
见 #254
