### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by cheng-shuai** [YXL76/cloudmusic-vscode#175]
**命令"Cloudmusic: 登录"导致错误 (command 'cloudmusic.signin' not found)**
设备：Windows10 20H2
卸载了几次还是这样

**Comment by YXL76** [comment]
麻烦贴一下`Bug report`模板里要求的信息

**Comment by cheng-shuai** [comment]
> 麻烦贴一下`Bug report`模板里要求的信息

请问一下要这么查看

**Comment by YXL76** [comment]
**Error information (Help->Toggle Developer Tools->Console)**
帮助->切换开发人员工具->Console

**Environment (Help->About)**
帮助->关于

**Comment by cheng-shuai** [comment]
workbench.desktop.main.js:sourcemap:3129 命令"Cloudmusic: 登录"导致错误 (command 'cloudmusic.signin' not found)

  | onDidChangeNotification | @ | workbench.desktop.main.js:sourcemap:3129
-- | -- | -- | --
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:3129
  | fire | @ | workbench.desktop.main.js:sourcemap:99
  | addNotification | @ | workbench.desktop.main.js:sourcemap:3194
  | error | @ | workbench.desktop.main.js:sourcemap:4940
  | accept | @ | workbench.desktop.main.js:sourcemap:2909
  | async function (async) |   |  
  | accept | @ | workbench.desktop.main.js:sourcemap:2909
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:1833
  | fire | @ | workbench.desktop.main.js:sourcemap:99
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:1240
  | fire | @ | workbench.desktop.main.js:sourcemap:99
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:1251

---

版本: 1.51.1 (user setup)
提交: e5a624b788d92b8d34d1392e4c4d9789406efe8f
日期: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by YXL76** [comment]
之前有正常使用过吗？

**Comment by cheng-shuai** [comment]
> 之前有正常使用过吗？

有的

**Comment by YXL76** [comment]
有使用代理软件吗？

**Comment by cheng-shuai** [comment]
> 有使用代理软件吗？

 没有,现在已经可以正常使用了.具体什么原因不太清楚.
谢谢了
