### ISSUE TITLE
3.7.5 更新后无法听到音乐

### ISSUE THREAD

**Issue by heartacker** [YXL76/cloudmusic-vscode#19]
**Describe the bug**
点击列表之后列队可以看到音乐播放列表,但是基本上没有声音.点击默认,没有任何反应, 点击私人电台也没有任何声音.
之前的版本是ok的.

另外,我多台电脑更新到3.7.5 都是这样的情况

**Environment (Help->About)**
版本: 1.48.0 (system setup)
提交: db40434f562994116e5b21c24015a2e40b2504e6
日期: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by YXL76** [comment]
请你尝试回滚至`3.7.4`，然后打开`$HOME/.vscode/extensions/yxl.cloudmusic-3.7.4/`，复制`build`文件夹，接着更新至`3.7.5`，并覆盖`$HOME/.vscode/extensions/yxl.cloudmusic-3.7.5/build`，检查是否可用。
另外，请检查控制台是否有任何错误信息。 @heartacker

**Comment by YXL76** [comment]
请问播放歌曲时，状态栏显示的是暂停还是播放，是否可以使用上一首/下一首。@heartacker

**Comment by heartacker** [comment]
> 请问播放歌曲时，状态栏显示的是暂停还是播放，是否可以使用上一首/下一首。@heartacker

也不知道为什么，现在好了。好奇怪，我后续看看出问题在反馈。但是当时真的是这样。

**Comment by YXL76** [comment]
请问`3.7.6`能正常使用吗？如果可以我将关闭此issue。 @heartacker

**Comment by heartacker** [comment]
> 请问`3.7.6`能正常使用吗？如果可以我将关闭此issue。 @heartacker 

可以了。3q
