### ISSUE TITLE
6.0.1一加载就停止host

### ISSUE THREAD

**Issue by heartacker** [YXL76/cloudmusic-vscode#199]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1876302/102229603-f401d500-3f26-11eb-8ead-b8f87cb5d13e.png)

**Error information (Help->Toggle Developer Tools->Console)**
V6.0.1

**Environment (Help->About)**
Paste the content in `Help->About`
版本: 1.52.0 (system setup)
提交: 940b5f4bb5fa47866a54529ed759d95d09ee80be
日期: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by YXL76** [comment]
请更新至`v6.0.2` @heartacker
