### ISSUE TITLE
歌单只有几首歌/歌曲只播放30秒（版权？）

### ISSUE THREAD

**Issue by hzfmer** [YXL76/cloudmusic-vscode#210]
**Describe the bug**
原本有几百首歌的歌单只有6-7首歌，刷新依旧是这几首。似乎是因为在海外版权限制无法播放？
请问有什么办法解决这个问题吗？
![image](https://user-images.githubusercontent.com/28425640/102941493-b1308780-4467-11eb-9f3d-0ce6db4d9518.png)

**Error information (Help->Toggle Developer Tools->Console)**
![image](https://user-images.githubusercontent.com/28425640/102941430-8b0ae780-4467-11eb-83de-35c1e0e62ecf.png)

**Environment (Help->About)**
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (6 days ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

**Comment by YXL76** [comment]
请问方便使用[NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)测试同一歌单的结果吗？如果一样，尝试设置[X-Real-IP](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e8%b0%83%e7%94%a8%e5%89%8d%e9%a1%bb%e7%9f%a5)看看是否有效 @hzfmer

**Comment by hzfmer** [comment]
@YXL76  非常抱歉，之前没有时间测试，就没有回复。刚刚发现更新之后已经修好了，谢谢！

**Comment by hzfmer** [comment]
但是好像有一个新的问题，不知道是不是有联系，`sign in` 和 `search`命令返回 error，但是其他的命令似乎都没问题。 就先不开新的issue了：
![image](https://user-images.githubusercontent.com/28425640/103195004-323bb480-4896-11eb-9dec-c94f224056cc.png)

**Comment by YXL76** [comment]
大概是初始化改残了，我考完试就修

**Comment by YXL76** [comment]
`sign in`命令可以用吧？ @hzfmer

**Comment by hzfmer** [comment]
@YXL76  对， `sign in` 是好的，真高效啊！

**Comment by hzfmer** [comment]
@YXL76 
好像还有一个版权问题，有些歌只会播放30s。这个好像已经有人解决，如[1](https://github.com/meng-chuan/Unlock-netease-cloud-music), [2](https://github.com/nondanee/UnblockNeteaseMusic), 不知道能不能吸收进来？
谢谢！

**Comment by YXL76** [comment]
> @YXL76
> 好像还有一个版权问题，有些歌只会播放30s。这个好像已经有人解决，如[1](https://github.com/meng-chuan/Unlock-netease-cloud-music), [2](https://github.com/nondanee/UnblockNeteaseMusic), 不知道能不能吸收进来？
> 谢谢！

已支持

**Comment by hzfmer** [comment]
> > @YXL76
> > 好像还有一个版权问题，有些歌只会播放30s。这个好像已经有人解决，如[1](https://github.com/meng-chuan/Unlock-netease-cloud-music), [2](https://github.com/nondanee/UnblockNeteaseMusic), 不知道能不能吸收进来？
> > 谢谢！
> 
> 已支持

谢谢！好像没有完全解决？比如搜索王菲的“笑忘书”，还是只有30s。

**Comment by YXL76** [comment]
你开启了替换音源吗？

**Comment by hzfmer** [comment]
> 你开启了替换音源吗？

是的，已经开启了：
![image](https://user-images.githubusercontent.com/28425640/107175151-f578d800-6980-11eb-98eb-4ac1bde3912d.png)

我后来发现是即使是搜索同样的歌：
![image](https://user-images.githubusercontent.com/28425640/107175306-59030580-6981-11eb-863e-a23320ff0a94.png)
第一个是不行的（只有30s），最后一行那个是可以的。

**Comment by YXL76** [comment]
大概缓存的问题，可以先尝试删除用户目录下的`.cloudmusic`文件夹看看有没有效果，之后会修复 @hzfmer

**Comment by hzfmer** [comment]
@YXL76  似乎是的，删除了`.cloudmusic`之后问题解决了。
