### ISSUE TITLE
我得一直无法登录

### ISSUE THREAD

**Issue by StephenChyi** [YXL76/cloudmusic-vscode#219]
**Describe the problem you encountered.**
A clear and concise description of what the question is.
![image](https://user-images.githubusercontent.com/42527566/103433026-ecc81000-4c24-11eb-9299-2a75bf48d8c3.png)
![image](https://user-images.githubusercontent.com/42527566/103433029-f3ef1e00-4c24-11eb-8da8-cfa7c684d217.png)
我的账号是neoamell@yeah.net

**Comment by YXL76** [comment]
能否提供控制台（`Help->Toggle Developer Tools->Console`）里的信息 @StephenChyi

**Comment by StephenChyi** [comment]
更新了登录方式后，邮箱密码可以登录了
