### ISSUE TITLE
邮箱账号无法登录，选择二维码弹不出来

### ISSUE THREAD

**Issue by StephenChyi** [YXL76/cloudmusic-vscode#249]
**Describe the bug**

**Error information (Help->Toggle Developer Tools->Console)**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`

**Environment (Help->About)**
Paste the content in `Help->About`
![image](https://user-images.githubusercontent.com/42527566/104991171-140e4200-5a59-11eb-8348-3dd8a881ae4a.png)
控制台报错图片
![image](https://user-images.githubusercontent.com/42527566/104991195-27211200-5a59-11eb-8d99-01b7811a821b.png)
VSCODE信息

**Comment by YXL76** [comment]
二维码弹不出来是没有页面还是有页面但是没有二维码

**Comment by StephenChyi** [comment]
直接没有页面

**Comment by StephenChyi** [comment]
![image](https://user-images.githubusercontent.com/42527566/104993611-1030ee80-5a5e-11eb-858b-322f2396208b.png)
![image](https://user-images.githubusercontent.com/42527566/104993624-1757fc80-5a5e-11eb-9f9d-898d33a39f03.png)
这是我装的插件，不知是否有影响

**Comment by YXL76** [comment]
我怎么觉得是你的网络有问题

**Comment by StephenChyi** [comment]
没有任何代理， 我肯定

**Comment by YXL76** [comment]
你尝试回滚到`5.x.x`版本，看看能不能登陆

**Comment by StephenChyi** [comment]
我试了所有5.XX的版本，都是相同的错

**Comment by YXL76** [comment]
你试一试`v2.1.2`能不能行，不然就是你的网络有问题，或者你的邮箱不能登陆（你可以去[Binaryify/NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi/issues)反馈）

**Comment by StephenChyi** [comment]
我等有时间换个网络环境试下吧，我的邮箱是可以在客户端登录的,这个报的错，好像是主机代理的问题啊

**Comment by StephenChyi** [comment]
![image](https://user-images.githubusercontent.com/42527566/104995799-cf3ad900-5a61-11eb-8681-2a4cdc923197.png)
2.1.2的报错

**Comment by YXL76** [comment]
感觉这个问题与你本机有关，根据一开始的报错应该就是网络问题。你还可以试试`vscode-insider`，也许是`node`的`bug`

**Comment by YXL76** [comment]
忘了你就而是`insider`。。。

**Comment by StephenChyi** [comment]
目前用的就是内部版本，原谅绿那个

**Comment by StephenChyi** [comment]
我已经证明了，是网络问题，我换一个网络就没有问题了，thk
