### ISSUE TITLE
日推歌曲列表添加到队列的步骤有些长

### ISSUE THREAD

**Issue by cantwork** [YXL76/cloudmusic-vscode#254]
有无更快捷的实现计划？
比如在队列bar右侧加个添加日推歌曲到播放队列按钮；
或者在初始化的时候，登录后直接在播放队列中加载日推；
~~再或者直接把日推歌曲列表作为一个歌单放到用户歌单bar下面。。~~

每次开始使用扩展，播放队列中都是空的，我的第一想法就是去把日推歌曲列表加到队列（~~收藏/红心列表都听腻了~~），不过这个步骤过于长了，差不多要经过五六次的点击才能开始听歌

**Comment by YXL76** [comment]
目前的方案是登录后自动加载每日推荐歌曲
