### ISSUE TITLE
搜索歌曲后，怎么播放？

### ISSUE THREAD

**Issue by Reregi** [YXL76/cloudmusic-vscode#268]
点击无效

**Comment by YXL76** [comment]
选择好要播放的歌曲添加到队列

**Comment by Reregi** [comment]
> 选择好要播放的歌曲添加到队列
是否只有相似歌曲才有多选添加到队列呢请问

**Comment by YXL76** [comment]
`相似歌曲`是什么意思？

**Comment by Reregi** [comment]
> `相似歌曲`是什么意思？

歌曲-详情 里面的 相似歌曲 点击后会出现5首的相似歌曲嘛 是可以多选 勾选后批量加进 队列
但是歌手-详情 里面的 热门歌曲却不可以多选

**Comment by YXL76** [comment]
嗯，要多选的话点所有歌曲

**Comment by Reregi** [comment]
thanks 那我关闭了

**Comment by hzfmer** [comment]
> 选择好要播放的歌曲添加到队列

请问一下，能做一个功能直接播放吗？或者添加到队首。因为场景很可能是，听一个歌单的时候，临时想添加一首歌播放。目前需要“加到队列，拉到最后，点击播放”，不太方便。

**Comment by YXL76** [comment]
将在`7.0.0`添加 @hzfmer

**Comment by hzfmer** [comment]
> 将在`7.0.0`添加 @hzfmer

感谢   @YXL76 !
不过这个更新好像把`Cloudmusic: Search`给弄不见了？。。
没有测试其他命令有没有受到影响。

**Comment by YXL76** [comment]
> > 将在`7.0.0`添加 @hzfmer
> 
> 感谢 @YXL76 !
> 不过这个更新好像把`Cloudmusic: Search`给弄不见了？。。
> 没有测试其他命令有没有受到影响。

是的，移除了，现在统一以账号按钮作为入口
