### ISSUE TITLE
1.49.0-insider 安装 cloudmusic v4.0.1 没有账号图标

### ISSUE THREAD

**Issue by OpenWaygate** [YXL76/cloudmusic-vscode#28]
**Describe the bug**

1.49.0-insider 安装 cloudmusic v4.0.1 没有账号图标

**Error information (Help->Toggle Developer Tools->Console)**

![image](https://user-images.githubusercontent.com/27287694/90984953-1607ce00-e5ab-11ea-8256-5f1b073cb07d.png)

**Environment (Help->About)**

Version: 1.49.0-insider (system setup)
Commit: 44ad54d9faa4604ab17628e8396e072258187737
Date: 2020-08-21T06:26:21.718Z
Electron: 9.2.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20175

cloudmusic v4.0.1

**Comment by YXL76** [comment]
请尝试安装[Visual C++](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)，之后再查看能否使用。 @OpenWaygate

**Comment by OpenWaygate** [comment]
安装之后出现账号图标了, 但登录时又出现了问题, 邮箱、手机和网上搜的共享号试了都登录失败, 甚至我点击账号图标后再点击<kbd>esc</kbd> 也会出现这个错误.

![image](https://user-images.githubusercontent.com/27287694/91153905-6ab66080-e6f3-11ea-97d8-898988a0fe68.png)

**Comment by YXL76** [comment]
请问你可以在stable`版可以请尝试一下。 @OpenWaygate

**Comment by OpenWaygate** [comment]
stable也不行, 和insider一样, 我账号的登录保护也是关闭的

Version: 1.48.1 (system setup)
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:12:13.244Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.20175

![image](https://user-images.githubusercontent.com/27287694/91156171-5fb0ff80-e6f6-11ea-9ec8-47bc4e54497a.png)

**Comment by YXL76** [comment]
这确实很奇怪，我晚些时候会进行一些测试。

**Comment by OpenWaygate** [comment]
我找到原因了, cfw的锅. 谢谢大佬!

![image](https://user-images.githubusercontent.com/27287694/91158603-786ee480-e6f9-11ea-9dcd-4227d15fca5a.png)

我又有了新的问题, 我自己有个网易云的proxy(使用的 [UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic)), vs code设置里填的格式是`ip:port`, 可以登录, 但侧栏的playlist全空了, 也搜索不到歌曲, 请问这个proxy会接管这个插件所有的请求吗?

**Comment by OpenWaygate** [comment]
我把proxy格式修改成 `http://ip:port`后可以使用了, 只是会员歌曲还是有`Network error`

**Comment by YXL76** [comment]
我想问问cfw的锅具体是什么，如何操作就可以正常使用。 @OpenWaygate

**Comment by YXL76** [comment]
关于`Network error`，会员歌曲是指本身帐号无法播放，通过`UnblockNeteaseMusic`解锁的歌曲吗？

**Comment by OpenWaygate** [comment]
cfw的分流规则里把网易云改成直连就好了, 之前出错是因为设置的走我的proxy.

会员歌曲就是黑胶会员歌曲, 运气好的话可以用`UnblockNeteaseMusic`听

**Comment by YXL76** [comment]
好的。关于`UnblockNeteaseMusic`，我日后可能会整合进扩展当中，不过这会是一个不小的工作。
