### ISSUE TITLE
当在环境变量中设置http_proxy时，且开启代理时，显示网络错误

### ISSUE THREAD

**Issue by mcwindy** [YXL76/cloudmusic-vscode#280]
当在环境变量中设置http_proxy时，且开启代理时，显示网络错误
v7.0.2

**Comment by YXL76** [comment]
代理端的问题，能贴一下控制台信息吗？
请问是什么代理，网易云的链接是被代理还是直连？ @mcwindy

**Comment by YXL76** [comment]
> 代理端的问题，能贴一下控制台信息吗？
> 请问是什么代理，网易云的链接是被代理还是直连？ @mcwindy

以及尝试设置`"http.proxyStrictSSL": false`

**Comment by mcwindy** [comment]
重启后问题没有了，感谢回复
