### ISSUE TITLE
在打开了媒体控制之后 使用媒体控制键没反应

### ISSUE THREAD

**Issue by GysdfHome** [YXL76/cloudmusic-vscode#288]
如题
机子是Surface

**Comment by YXL76** [comment]
目前相关代码都注释了，因为在本机模块后端的迁移有部分还未完成
我会关注[neon-bindings/neon#596](https://github.com/neon-bindings/neon/issues/596)，等完成后我就会补上媒体控制的支持

**Comment by YXL76** [comment]
请检查`v7.2.0`能否正常使用
