### ISSUE TITLE
希望能提供历史版本的cloudmusic-vscode

### ISSUE THREAD

**Issue by exyexin** [YXL76/cloudmusic-vscode#290]
自己在用HUAWEI-liteos-studio【基于vscode-1.45.7】，所能下载到的cloudmusic-vscode好像都不能兼容
不知道您是否有开发过该版本的插件。谢谢

**Comment by YXL76** [comment]
用不了是指插件是灰色的吗？

**Comment by exyexin** [comment]
谢谢回复
HUAWEI-liteos-studio安装插件似乎并不能直接通过应用商店进行下载，所以需要进入[https://marketplace.visualstudio.com/items?itemName=yxl.cloudmusic](url)下的Version History进行下载vsix文件后，自行添加至IDE
此时会提示“无法安装扩展“yxl.cloudmusic”，因为它与 VS Code“1.45.7”不兼容。”
所以希望能找到较早版本的插件

**Comment by YXL76** [comment]
我看了一下，第一次开发本拓展时的版本是`1.46.0`

**Comment by exyexin** [comment]
啊，还挺遗憾的
如果可以的话，能不能发给我一份呢，万一可以用

**Comment by YXL76** [comment]
可以尝试`clone`本仓库，`package.json`这两行修改为对应的`vscode`版本
https://github.com/YXL76/cloudmusic-vscode/blob/e9858e9bdd56f81b8ca19caaa7941f2aa04627f0/package.json#L8
https://github.com/YXL76/cloudmusic-vscode/blob/e9858e9bdd56f81b8ca19caaa7941f2aa04627f0/package.json#L845

运行

```sh
yarn
yarn dlx vsce package --no-yarn
```

可以得到`.vsix`文件

**Comment by exyexin** [comment]
好的，我去试一下，谢谢

**Comment by YXL76** [comment]
对了，`clone`完要先加上本机文件，可以直接用解压软件打开`.vsix`，把里面的`build`文件夹解压到项目根目录

或者，如果有`rust`环境，可以直接运行
```sh
cargo build --release
```
