### ISSUE TITLE
邮箱登录失败

### ISSUE THREAD

**Issue by nondanee** [YXL76/cloudmusic-vscode#3]
https://github.com/YXL76/cloudmusic-vscode/blob/f92a21f4de02a703c3a4d5f0ae44f94dca888f73/src/manager/accountManager.ts#L50-L54

参数应该是 email

```diff
-     username: account, 
+     email: account, 
```

**Comment by YXL76** [comment]
> https://github.com/YXL76/cloudmusic-vscode/blob/f92a21f4de02a703c3a4d5f0ae44f94dca888f73/src/manager/accountManager.ts#L50-L54
> 
> 参数应该是 email
> 
> ```diff
> -     username: account, 
> +     email: account, 
> ```

感谢。应该已在`v2.1.2`修复
