### ISSUE TITLE
提一个小建议

### ISSUE THREAD

**Issue by cheng-shuai** [YXL76/cloudmusic-vscode#30]
cloudmusic这个插件只有在cloudmusic的这一个界面才会自动切换音乐，而换成了其他的界面，如资源管理器时，就不会自动切换音乐，然后自动暂停音乐，连按按钮也不会切换歌曲，只有切换为cloudmusic这个界面才会切换
**希望可以在任何界面都可以切换音乐**

**Comment by YXL76** [comment]
能请你查看一下`3.x.x`版本能做到吗？ @cheng-shuai

**Comment by cheng-shuai** [comment]
> 能请你查看一下`3.x.x`版本能做到吗？ @cheng-shuai 

经过尝试，3.7.7版本可以解决

**Comment by cheng-shuai** [comment]
为什么最新版本的确不能使用呢？

**Comment by YXL76** [comment]
> 为什么最新版本的确不能使用呢？

因为新版我把歌曲切换写到了视图更新里，这样会有视觉提示，只是没想到是视图懒更新的。

**Comment by cheng-shuai** [comment]
> > 为什么最新版本的确不能使用呢？
> 
> 因为新版我把歌曲切换写到了视图更新里，这样会有视觉提示，只是没想到是视图懒更新的。

下一版本可以恢复使用吗？

**Comment by YXL76** [comment]
请检查`4.2.1` @cheng-shuai

**Comment by cheng-shuai** [comment]
>  请检查`4.2.1` @cheng-shuai 

已可以使用，非常感谢
