### ISSUE TITLE
Macos可以使用

### ISSUE THREAD

**Issue by ab15963qw** [YXL76/cloudmusic-vscode#317]
**Describe the problem you encountered.**
A clear and concise description of what the question is.
你好！我想問一下，我安裝完插件之後。可是沒有畫面出來？
<img width="284" alt="截圖 2021-02-24 上午1 23 12" src="https://user-images.githubusercontent.com/36786222/108881994-de9fda00-763e-11eb-92cd-6db04fb91f89.png">

**Comment by YXL76** [comment]
请问登录了吗？如果登录了请查看控制台是否有错误信息 @ab15963qw

**Comment by ab15963qw** [comment]
你好，我連登綠都沒辦法，沒有出現登綠圖案
<img width="1520" alt="截圖 2021-02-24 上午11 30 47" src="https://user-images.githubusercontent.com/36786222/108943424-c017fe00-7693-11eb-9e25-0ebb75835ca4.png">

**Comment by YXL76** [comment]
提供一下错误信息（Help->Toggle Developer Tools->Console）和使用环境（Help->About）

**Comment by ab15963qw** [comment]
好 错误信息
<img width="553" alt="截圖 2021-02-24 下午12 41 57" src="https://user-images.githubusercontent.com/36786222/108948629-cd39ea80-769d-11eb-97dc-ade5170bb64b.png">
使用环境
<img width="427" alt="截圖 2021-02-24 下午12 42 08" src="https://user-images.githubusercontent.com/36786222/108948674-dfb42400-769d-11eb-89bc-b7901118a61c.png">

**Comment by YXL76** [comment]
类似于 #249 ，`HTTPS API`的问题，可以试试更换网络环境

**Comment by ab15963qw** [comment]
好
