### ISSUE TITLE
请问有考虑过将歌词显示放入一个单独的编辑器吗

### ISSUE THREAD

**Issue by chenxizhou233** [YXL76/cloudmusic-vscode#324]
加了这个就可以基本告别网易云了

**Comment by YXL76** [comment]
已有

**Comment by YXL76** [comment]
是指单纯的文本，还是有位置指示

**Comment by chenxizhou233** [comment]
单纯的文本
就是现在只能在底栏看，有点小，同时也不能在开其他应用时看歌词。


> 是指单纯的文本，还是有位置指示

**Comment by chenxizhou233** [comment]
![例子](https://wx1.sinaimg.cn/large/008g9FOgly1gnzwqw1c92j31z4172grm.jpg)

**Comment by YXL76** [comment]
一次只显示一行，会实时更新的意思？

**Comment by chenxizhou233** [comment]
是的

**Comment by YXL76** [comment]
已在`v7.2.0`中实现，在歌词`QickPick`中添加`Show in editor`选项

**Comment by chenxizhou233** [comment]
感谢神犇！！！%%%%%
，谢谢！
发送自 Windows 10 版邮件应用

发件人: 兰陈昕
发送时间: 2021年3月4日 0:25
收件人: YXL76/cloudmusic-vscode
抄送: chenxizhou233; State change
主题: Re: [YXL76/cloudmusic-vscode] 请问有考虑过将歌词显示放入一个单独的编辑器吗 (#324)

已在v7.2.0中实现，在歌词QickPick中添加Show in editor选项
