### ISSUE TITLE
当只是播放一首本地歌曲的时候无法暂停

### ISSUE THREAD

**Issue by allinu** [YXL76/cloudmusic-vscode#329]
**Describe the bug**
当只播放一首歌曲的时候，遇到这种情况是播放的本地歌曲，无法暂停，点击暂停以及通过Command + Shift + P 中的命令均无法实现暂停

![image](https://user-images.githubusercontent.com/32992109/109642118-8b251300-7b8d-11eb-84cb-d244089700f9.png)

**Error information (Help->Toggle Developer Tools->Console)**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`

没有显示，只是无法暂停

![image](https://user-images.githubusercontent.com/32992109/109642189-9bd58900-7b8d-11eb-839e-8c93363e8422.png)

**Environment (Help->About)**
Paste the content in `Help->About`

```
版本: 1.53.2
提交: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
日期: 2021-02-11T11:45:54.515Z (2 周前)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

**Comment by YXL76** [comment]
请检查`v7.2.0`

**Comment by allinu** [comment]
> 请检查`v7.2.0`

已解决，非常感谢😊
