### ISSUE TITLE
喜欢按钮点击失效

### ISSUE THREAD

**Issue by allinu** [YXL76/cloudmusic-vscode#330]
**Describe the bug**
无法通过点击底部状态栏的喜欢按钮实现添加到`我喜欢`歌单
点击状态栏的歌曲名，在弹出来的窗口添加到喜欢也无反应，但是通过添加到歌单是可以添加到`我喜欢`的

![image](https://user-images.githubusercontent.com/32992109/109827852-10382700-7c77-11eb-8a44-3d4cabd816c7.png)

**Error information (Help->Toggle Developer Tools->Console)**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`

![image](https://user-images.githubusercontent.com/32992109/109828211-64dba200-7c77-11eb-9fec-08182bddcc10.png)

**Environment (Help->About)**
Paste the content in `Help->About`

```
版本: 1.53.2
提交: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
日期: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

**Comment by YXL76** [comment]
见[Binaryify/NeteaseCloudMusicApi#1151](https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1151)
下个版本将修复

**Comment by YXL76** [comment]
请检查`v7.2.0`

**Comment by allinu** [comment]
> 请检查`v7.2.0`

好的，谢谢您😊

**Comment by hzfmer** [comment]
> 请检查`v7.2.0`

我想确认一下，“Like”的功能修复似乎没有修复好？我用的是`7.2.0`，还是不行。
另外，这个“喜欢”的 icon 不太容易区分两种状态，如果没有弹出提醒“喜欢成功”的话，几乎不知道是否添加成功。我是在喜欢 list 里找了一遍才确定没有加进去。

谢谢！

**Comment by YXL76** [comment]
我这边使用并没有问题

**Comment by hzfmer** [comment]
> 我这边使用并没有问题

测试了一下，是一部分歌曲不可以。可能是因为是VIP，或者已经被下架了（但是还能听）之类的。。

**Comment by YXL76** [comment]
在`v7.5.0`中添加了喜欢结果的提示，并且对于无法操作的歌曲，按钮会显示无法操作的图标 @hzfmer
