### ISSUE TITLE
建议记忆音量设置以及添加歌单缓存

### ISSUE THREAD

**Issue by NekodRider** [YXL76/cloudmusic-vscode#34]
**Is your feature request related to a problem? Please describe.**
1. 现在启动后默认音量是85 但是我这合适的音量是15-30左右 每次打开都要手动调很麻烦
2. 歌单歌很多的情况下(1k-2k)打开大约要加载10-20秒

**Describe the solution you'd like**
1. 音量记忆历史设置 或者搞一个 默认音量值
2. 歌单也加入缓存

**Comment by YXL76** [comment]
目前歌单内容已使用缓存，但因为歌单内容是动态的，所以缓存都带有时效，所以初始化后的第一次还是要从服务器获取数据。 @NekodRider

**Comment by NekodRider** [comment]
的确测试的是reload窗口后的第一次加载时间，毕竟之后直接读取的 treeView 里面的嘛。
我想的是改成跟歌曲歌词一样的缓存机制，但.cloudmusic/cache 下没看到歌单的缓存来着，缓存可以通过 trackUpdateTime 判断需不需要更新。

**Comment by YXL76** [comment]
大部分网络请求都有缓存机制，是基于内存而非本地缓存。关于获取速度慢的问题，我会尝试合并请求和修改数据处理部分来提高速度。 @NekodRider

**Comment by YXL76** [comment]
已在`4.5.0`中添加了音量记忆，获取歌单歌曲的速度应该会有提升。@NekodRider

**Comment by NekodRider** [comment]
嗯 测试了一下 `4.5.0` 比以前加载快了 谢谢
