### ISSUE TITLE
播放收藏夹的歌曲时经常“网络错误”

### ISSUE THREAD

**Issue by Akashiya-Chime** [YXL76/cloudmusic-vscode#35]

**Comment by NekodRider** [comment]
我也遇到了这个问题 主要是网络错误之后有时候UI也会卡住 无法重置 只能reload window 回去以后我补充下报错信息

**Comment by YXL76** [comment]
这确实是一个问题，可惜拓展目前没有任何`Debug`的能力，我应该要先添加一个`Debug`模式来帮助我们定位错误。 @NekodRider @Akashiya-Chime
