### ISSUE TITLE
在切换进入和离开VMWare Workstation时会改变播放状态

### ISSUE THREAD

**Issue by qwerty250** [YXL76/cloudmusic-vscode#361]
**Describe the bug**
宿主机的VSCode使用cloudmusic播放音乐时，如果切换进入VMWare虚拟机，会导致音乐中断。离开虚拟机时，音乐又会突然响起。

**Error information (Help->Toggle Developer Tools->Console)**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容

**Environment (Help->About)**
宿主机：Windows 10
VM软件：VMware® Workstation 15 Pro
虚拟机：Windows 10

**Comment by YXL76** [comment]
目前计划在下一个MAJOR版本中重写播放器，所以暂时不解决此bug
