### ISSUE TITLE
没绑定邮箱，手机号绑的gv一直登入失败

### ISSUE THREAD

**Issue by leezm** [YXL76/cloudmusic-vscode#38]
如题。
手机号是gv的话如何登入？
邮箱也没绑定，因为没有网易邮箱...
### 有没有其他登入方式了...

**Comment by leezm** [comment]
> 那请问你是如何登录官方app的？ @leezm

官当登入方式有手机、邮箱、绑定的微信或QQ登入，一般用绑定账号登入方便。
官方的手机登入前面会让选国码的，就是能改默认的+86

**Comment by YXL76** [comment]
好的，目前绑定登陆无法实现，我近期会添加输入手机国家码的功能。 @leezm

**Comment by leezm** [comment]
> 好的，目前绑定登陆无法实现，我近期会添加输入手机国家码的功能。 @leezm 

😄上班摸🐟又多了个选择

**Comment by YXL76** [comment]
请你测试一下`4.6.0`能否正常登录。 @leezm

**Comment by leezm** [comment]
> 请你测试一下`4.6.0`能否正常登录。 @leezm 

明天试吧🥱

**Comment by leezm** [comment]
> 请你测试一下`4.6.0`能否正常登录。 @leezm

4.6登入成功了✔
