### ISSUE TITLE
local build faild

### ISSUE THREAD

**Issue by yihong0618** [YXL76/cloudmusic-vscode#380]
**Describe the bug**
我想本地 build 一份测试，如果我安装了 `cloudmusic`  是能 build 成功的 (我是在 vscode 里按 f5 build)
但如果我把插件卸载了，再 build 会报错（同样按f5）
错误信息
```
Activating extension 'YXL.cloudmusic' failed: Can not find module '/root/cloudmusic-vscode/build/linux.node'
Require stack:
- /root/cloudmusic-vscode/dist/extension.js
- /root/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/loader.js
- /root/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/bootstrap-amd.js
- /root/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/bootstrap-fork.js.
```

**Error information (Help->Toggle Developer Tools->Console)**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容

![image](https://user-images.githubusercontent.com/15976103/112608508-5e46e180-8e55-11eb-8587-096895b85224.png)

**Environment (Help->About)**
Paste the content in `Help->About`
windows 10 和 wsl 都尝试了都是这个错误。

node 版本 
v14.4.0

**Comment by YXL76** [comment]
还要编译native module
如果看得懂github actions的语法，[release.yml](https://github.com/YXL76/cloudmusic-vscode/blob/master/.github/workflows/release.yml)是完整的构建流程

**Comment by yihong0618** [comment]
明白了，谢谢。

**Comment by yihong0618** [comment]
感谢你的解答
@YXL76 
![image](https://user-images.githubusercontent.com/15976103/112719532-5873fd80-8f34-11eb-8abf-02e2c8de7cac.png)

对不起我不太理解这块，你这个 release 中跑的这两个 upload 和 download 
可以在本地运行么（还是必须跑 Actions）？

我本地试了下 如果直接 cp  libnative.so build/linux.node 再 f5 build, 是报另一个错误。
![image](https://user-images.githubusercontent.com/15976103/112719587-8fe2aa00-8f34-11eb-9e57-ff9f26b05671.png)

![image](https://user-images.githubusercontent.com/15976103/112719629-c4566600-8f34-11eb-97ba-0c77f82ec7d6.png)

不好意思，第一次接触 rust...打扰你了。

**Comment by YXL76** [comment]
在项目目录中运行这两个命令就可以了

```bash
cargo build --release
cp target/release/libnative.so build/linux.node
```

还有要注意选择`Run Extension`

![image](https://user-images.githubusercontent.com/43405544/112720610-5f057380-8f3a-11eb-87b5-20709159d613.png)

如果你已经这么做了还是不行，麻烦提供一下系统信息

**Comment by yihong0618** [comment]
Hi~
![image](https://user-images.githubusercontent.com/15976103/112720811-9fb1bc80-8f3b-11eb-877d-4f6d3ec48fc7.png)
我上面就是这么做的。 

系统信息是 wsl(wsl1)

![image](https://user-images.githubusercontent.com/15976103/112720850-cff95b00-8f3b-11eb-81c7-885c6d69271e.png)

**Comment by YXL76** [comment]
参考[RustAudio/rodio#354](https://github.com/RustAudio/rodio/issues/354)
推荐在宿主机编译

**Comment by yihong0618** [comment]
@YXL76 
明白了，感谢。我试试 window10.

**Comment by yihong0618** [comment]
win10 本地 build 成功了，感谢解答。

**Comment by yihong0618** [comment]
Sponsor 了一下。感谢作者的优雅方案~
考虑用在我的一个 vscode 玩具上~

**Comment by YXL76** [comment]
感谢
