### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by mcwindy** [YXL76/cloudmusic-vscode#384]
回退后发现7.0.0有的cloudmusic:login登陆在7.7.1没有了，导致无法登录，而且会报错

![image](https://user-images.githubusercontent.com/40684304/112750108-1b257380-8ff9-11eb-8d2b-2380b0756d37.png)

**Comment by mcwindy** [comment]
版本: 1.55.0-insider (user setup)
提交: d06d2f1d6245ce00b1c36a9cd81a9087d225173e
日期: 2021-03-26T14:01:14.867Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by YXL76** [comment]
`Cloudmusic:login`命令已删除

**Comment by mcwindy** [comment]
那要怎么登陆呢（

**Comment by YXL76** [comment]
![image](https://user-images.githubusercontent.com/43405544/112758501-58056080-9021-11eb-8b42-ca3020eec9c9.png)

**Comment by mcwindy** [comment]
并没有显示这个账号 右下角也没有弹出sign in

**Comment by YXL76** [comment]
暂时不能复现，可能相关的issue[microsoft/vscode#110171](https://github.com/microsoft/vscode/issues/110171)

**Comment by yihong0618** [comment]
我也遇到了这个 bug.

且本地 build 也会出现。猜测可能是用和 GitHub 一样的登陆机制导致的。

目前还尝试了：

1. 删除插件重新安装 —— failed
2. 强行删除登陆地 cache global state —— failed
3. 删除 vscode 重新安装 —— failed

---

个人觉得加一个登陆 command 比较好，猜测遇到这个情况还算普遍。

**Comment by YXL76** [comment]
请问一下，能帮忙调试一下哪里抛出错误，错误又是什么呢？@yihong0618

**Comment by yihong0618** [comment]
@YXL76 
错误跟一楼截图一样。

没有登陆的图标（之前是有的，参加我上一个 issue 昨天突然不好用）
![image](https://user-images.githubusercontent.com/15976103/113083073-269db800-920e-11eb-86db-fd0899fe85d7.png)

**Comment by yihong0618** [comment]
@YXL76 
我下午有时间尝试下添加把 cloudmusic.account 添加到 command 里看看能调出不。

**Comment by YXL76** [comment]
好的，主要是这个错误是哪里抛出的，会不会是`secrets`的问题

**Comment by yihong0618** [comment]
不是。现在的情况是 extension 没进去。

![image](https://user-images.githubusercontent.com/15976103/113085316-2c959800-9212-11eb-9c63-886c22efacbd.png)

选择 catch exception 的话报这个错误。
![image](https://user-images.githubusercontent.com/15976103/113085244-0ec83300-9212-11eb-888e-3d2cc66fd7db.png)

**Comment by YXL76** [comment]
那可以测试一下是否由其他拓展引起

**Comment by yihong0618** [comment]
不是，我删掉了全部拓展。还是一样

**Comment by mcwindy** [comment]
我也是报decryption failed的error

**Comment by haozihong** [comment]
今天vscode更新了一下，不能登录了（之前都没注意到login被移除了）。
左下角的acounts里看不到这个extension，不过能看到github，也能登录。

**Comment by YXL76** [comment]
请检查`7.7.2`

**Comment by yihong0618** [comment]
@YXL76 

可以了。

**Comment by ram16g** [comment]
为什么我这里还是 不行，没有变化

**Comment by yihong0618** [comment]
@ram16g 
删除插件重新安装试验一下？

**Comment by ram16g** [comment]
卸载vscode 和卸载 扩展都试了，还是不行 :(

**Comment by mcwindy** [comment]
我现在可以正常登陆了

**Comment by mcwindy** [comment]
在更新7.7.2之后

**Comment by mcwindy** [comment]
在更新7.7.2之后

**Comment by mcwindy** [comment]
在更新7.7.2之后

**Comment by aoeiuv-liu** [comment]
![image](https://user-images.githubusercontent.com/20061353/113510820-34956500-958f-11eb-8c9f-528a6afd2a11.png)
7.7.2 无法登陆

**Comment by aoeiuv-liu** [comment]
![image](https://user-images.githubusercontent.com/20061353/113510853-64dd0380-958f-11eb-83bd-ca8025c54d40.png)
系统是 arch+kde

**Comment by YXL76** [comment]
请问以前有使用过本插件吗？ @aoeiuv-liu

**Comment by YXL76** [comment]
以及音频后端有使用JACK吗？ @aoeiuv-liu

**Comment by aoeiuv-liu** [comment]
有的，之前使用的是上一个版本，之前重装也会登陆不上，但是只需要重新禁用启用就可以正常登陆了。没装JACK @YXL76

**Comment by aoeiuv-liu** [comment]
![image](https://user-images.githubusercontent.com/20061353/113511913-cc498200-9594-11eb-8964-33cafc8675e2.png)

**Comment by YXL76** [comment]
麻烦测试一下`7.0.0`可以使用吗？如果不可以，可以测试`lts`或`zen`内核

**Comment by aoeiuv-liu** [comment]
好神奇！刚才点进去又可以登陆了。估计是之前没加载完全。
![image](https://user-images.githubusercontent.com/20061353/113512062-83de9400-9595-11eb-8b01-422da6f31960.png)

**Comment by aoeiuv-liu** [comment]
等了差不多半个小时。。。。
