### ISSUE TITLE
在多个 Code 窗口间同步状态

### ISSUE THREAD

**Issue by yume-chan** [YXL76/cloudmusic-vscode#388]
**Is your feature request related to a problem? Please describe.**

现在如果同时打开多个 Code 窗口，播放器的状态是不同步的，甚至可以同时播放多首歌曲。

![image](https://user-images.githubusercontent.com/1330321/113089549-708c9b00-921a-11eb-8b58-551d0e4be20b.png)

**Describe the solution you'd like**

在多个 Code 窗口间同步状态，如果能在 stable 和 insiders 版之间同步更好

**Additional context**

另外现在在重新加载 Code 窗口（例如打开 Workspace，Reload Window 等）都会丢失所有播放状态，如果有个较为独立的 server，也可以避免这种情况

**Comment by YXL76** [comment]
这个问题还比较难实现。因为现在没有办法分辨用户是重启还是关闭，所以每次操作一定会先停止拓展

**Comment by YXL76** [comment]
大概构思了几种方案，但是都不能完美解决问题。欢迎大家在此讨论。

**Comment by yume-chan** [comment]
参考 Code 的终端实现，肯定需要一个单独的 server，然后用 named pipe/socket 通信。可以考虑用 Rust 实现一个，把现在的播放部分代码独立出来

通过扩展的 activate 和 deactivate 方法计数当前有几个 Code 窗口，在最后一个窗口退出时结束 server

但是有信息称 reload window 不会触发扩展的 deactivate，需要实际实验

如果要做到在只有一个 Code 窗口时 reload，还能连上原来的 server，只靠扩展 API 应该做不到。Code 的终端依赖了内部的 Lifecycle Service 可以获取到退出原因，如果是 reload 则 retain 终端进程，之后再 attach。但是这个信息并不会暴露给扩展。

仔细想想感觉这似乎就是实现了一个能通过 IPC 控制的网易云音乐播放器，和作为 Code 扩展的 design goal 可能有些冲突。

**Comment by YXL76** [comment]
而且现在我的思路是之后的版本里尽可能用wasm代替native

**Comment by YXL76** [comment]
server 如果作为子进程的的话应该也是会被 terminate 吧

**Comment by yume-chan** [comment]
子进程没有问题，比如 Node.js 可以在 spawn 的时候指定 detached option 解除 parent process 关系，各个 OS 也都有提供 API

https://nodejs.org/api/child_process.html#child_process_options_detached

**Comment by takayama-lily** [comment]
> 参考 Code 的终端实现，肯定需要一个单独的 server，然后用 named pipe/socket 通信。可以考虑用 Rust 实现一个，把现在的播放部分代码独立出来
> 
> 通过扩展的 activate 和 deactivate 方法计数当前有几个 Code 窗口，在最后一个窗口退出时结束 server
> 
> 但是有信息称 reload window 不会触发扩展的 deactivate，需要实际实验
> 
> 如果要做到在只有一个 Code 窗口时 reload，还能连上原来的 server，只靠扩展 API 应该做不到。Code 的终端依赖了内部的 Lifecycle Service 可以获取到退出原因，如果是 reload 则 retain 终端进程，之后再 attach。但是这个信息并不会暴露给扩展。
> 
> 仔细想想感觉这似乎就是实现了一个能通过 IPC 控制的网易云音乐播放器，和作为 Code 扩展的 design goal 可能有些冲突。

最后一个窗口reload时可以设一个超时退出，如果这段时间里又回来了就不用退出。

**Comment by takayama-lily** [comment]
不过为什么不使用globalStorage，不同窗口使用的都是同一个本地存储，创建lock文件就可以了。

**Comment by yume-chan** [comment]
如果播放器是在某一个窗口的 extension host 里，其它窗口和这个窗口同步，当这个窗口被关闭的时候播放会暂停（至少暂停一小段时间，直到另一个窗口接替播放的任务），而其它窗口关闭就不会
