### ISSUE TITLE
[feat] 可以添加 remote play 么？

### ISSUE THREAD

**Issue by yihong0618** [YXL76/cloudmusic-vscode#389]
简洁明了地描述您想要的功能。

之前用过 musicbox, 其中 musicbox 用的是 mpg123 的解决方案，mpg123 是可以播放远程的 MP3 的，但我注意到 rodio 是不可以的，但是有人已经在做了并且几乎做完了。
见这个 pr.
https://github.com/RustAudio/rodio/pull/282
如果可以的话，感觉比现在先下载再用 tmp dir 的方式要好一些。

**Comment by YXL76** [comment]
`v8.0.0`后将不再使用`rodio`，见 #344 ，而且先下载只要是因为防止本地缓存重复下载

**Comment by YXL76** [comment]
`v8.0.0`后将不再使用`rodio`，见 #344 ，而且先下载只要是因为防止本地缓存重复下载

**Comment by yihong0618** [comment]
学到了，谢谢。

**Comment by yihong0618** [comment]
尝试 remote 也遇到这个问题了。。。
https://github.com/RustAudio/rodio/issues/310

**Comment by YXL76** [comment]
见[CHANGELOG](https://github.com/RustAudio/cpal/blob/master/CHANGELOG.md#version-0120-2020-07-09)。因为移除了`EventLoop`，所以如果不想阻塞主进程，可以使用[thread](https://doc.rust-lang.org/std/thread/)

**Comment by yihong0618** [comment]
谢谢～
