### ISSUE TITLE
vscode 1.55.0 无法初始化

### ISSUE THREAD

**Issue by ram16g** [YXL76/cloudmusic-vscode#392]
vscode 1.55.0 无法初始化，已经安装了c++库，系统是  win10 x64

**Comment by ram16g** [comment]
重新安装了 1.54.3 还是不行，求正确使用姿势

**Comment by yihong0618** [comment]
https://github.com/YXL76/cloudmusic-vscode/issues/384

**Comment by YXL76** [comment]
请检查`7.7.2`

**Comment by ram16g** [comment]
更新到最新的 7.7.2，还是不能初始化，也没有找到登录入口

**Comment by YXL76** [comment]
贴上错误信息，vscode版本之类的信息

**Comment by ram16g** [comment]
系统信息
![image](https://user-images.githubusercontent.com/11473136/113646274-16c51e80-96bb-11eb-83f5-645c85c6aa9b.png)
截图
![image](https://user-images.githubusercontent.com/11473136/113646317-2d6b7580-96bb-11eb-918f-77096f1d6805.png)
没有任何报错信息

**Comment by YXL76** [comment]
错误信息查看：`Help->Toggle Developer Tools->Console`（帮助->切换开发者工具->控制台） @ram16g

**Comment by ram16g** [comment]
原来这样可以查看报错信息 
![image](https://user-images.githubusercontent.com/11473136/113651301-52b0b180-96c4-11eb-9a75-0513456b67b7.png)

**Comment by YXL76** [comment]
请问7.0.0之后的版本可以使用吗？请告诉我最新可以使用的版本

**Comment by ram16g** [comment]
1到7 所有版本都试了，均不能正常初始化，都会报错

**Comment by yihong0618** [comment]
@ram16g 
看起来是音频设备的原因。meizhaodao没找到音频设备。你可以看看你的电脑的音频设备设置。
![image](https://user-images.githubusercontent.com/15976103/113653355-43cbfe00-96c8-11eb-9a8c-c9640b049826.png)

**Comment by ram16g** [comment]
是的，我插上耳机就可以了 ：）
