### ISSUE TITLE
能否支持使用ffplay或者LAVFilters作为播放器？

### ISSUE THREAD

**Issue by YexuanXiao** [YXL76/cloudmusic-vscode#4]
rt，ffplay或者LAVFilters显然是一种比VLC或者MPV更轻便的选择，能否支持使用ffplay或者LAVFilters作为播放器？谢谢！

**Comment by YXL76** [comment]
> rt，ffplay或者LAVFilters显然是一种比VLC或者MPV更轻便的选择，能否支持使用ffplay或者LAVFilters作为播放器？谢谢！

关于播放器依赖将是`3.0.0`版本重点处理的问题，现阶段的想法是实现一个轻量播放器，以后的插件将自带二进制文件，就不依赖外部播放器了

**Comment by YXL76** [comment]
而且`ffplay`和`LAVFilters`似乎没有通信机制，虽然能通过进程控制实现播放/暂停，但是音量/进度调节就无能为力了
