### ISSUE TITLE
在私人FM状态，点击删除按钮没有反应

### ISSUE THREAD

**Issue by wksj007** [YXL76/cloudmusic-vscode#415]
在私人FM状态，点击删除按钮没有反应
![图片](https://user-images.githubusercontent.com/13026323/116374504-e9ded400-a840-11eb-930e-37d36da72bbd.png)

**Comment by wksj007** [comment]
版本: 1.55.2 (system setup)
提交: 3c4e3df9e89829dce27b7b5c24508306b151f30d
日期: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by YXL76** [comment]
期望的行为是跳过当前歌曲吗？

**Comment by wksj007** [comment]
嗯，是的。

**Comment by YXL76** [comment]
好的，下一个版本将会添加
