### ISSUE TITLE
添加不了本地曲库？

### ISSUE THREAD

**Issue by PhoenixNest** [YXL76/cloudmusic-vscode#417]
添加本地目录后不显示音乐文件
![image](https://user-images.githubusercontent.com/46096203/116417540-ef9ede80-a86d-11eb-86e7-2e1727de7471.png)

**Comment by YXL76** [comment]
首先，暂时不支持子目录。其次，目前只支持mp3，flac

**Comment by YXL76** [comment]
先确实是不是这些问题

**Comment by PhoenixNest** [comment]
芜湖，可以了，美滋滋

**Comment by YXL76** [comment]
最新版本支持子目录
