### ISSUE TITLE
command 'cloudmusic.account' not found

### ISSUE THREAD

**Issue by cruie** [YXL76/cloudmusic-vscode#418]
command 'cloudmusic.account' not found

**Comment by YXL76** [comment]
Maybe you can restart vscode

**Comment by SanQiG** [comment]
同样的问题，重启也没用

**Comment by SanQiG** [comment]
> vscode
同样的问题，重启也没用

**Comment by SanQiG** [comment]
> Maybe you can restart vscode

同样的问题，重启也没用...

**Comment by YXL76** [comment]
> > Maybe you can restart vscode
> 
> 同样的问题，重启也没用...

其他地方可以正常使用吗

**Comment by lilirg** [comment]
我也遇到同样的问题，从命令面板进入也会报错。

**Comment by YXL76** [comment]
不能复现，能有更详细的信息吗？比如错误信息、系统环境、拓展信息之类的

**Comment by WuLiangXiaoSeng** [comment]
> 不能复现，能有更详细的信息吗？比如错误信息、系统环境、拓展信息之类的
版本: 1.56.1 (user setup)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

第一次使用，点击登录按钮会弹出这条错误信息

**Comment by YXL76** [comment]
> > 不能复现，能有更详细的信息吗？比如错误信息、系统环境、拓展信息之类的
> > 版本: 1.56.1 (user setup)
> > Electron: 12.0.4
> > Chrome: 89.0.4389.114
> > Node.js: 14.16.0
> > V8: 8.9.255.24-electron.0
> > OS: Windows_NT x64 10.0.19042
> 
> 第一次使用，点击登录按钮会弹出这条错误信息

意思是所有功能都不能使用吗？

**Comment by YXL76** [comment]
错误信息
- `Help->Toggle Developer Tools->Console`（帮助->切换开发者工具->控制台）
- `%homepath%/.cloudmusic/err.log`

**Comment by WuLiangXiaoSeng** [comment]
> > > 不能复现，能有更详细的信息吗？比如错误信息、系统环境、拓展信息之类的
> > > 版本: 1.56.1 (user setup)
> > > Electron: 12.0.4
> > > Chrome: 89.0.4389.114
> > > Node.js: 14.16.0
> > > V8: 8.9.255.24-electron.0
> > > OS: Windows_NT x64 10.0.19042
> > 
> > 
> > 第一次使用，点击登录按钮会弹出这条错误信息
> 
> 意思是所有功能都不能使用吗？

我看了错误信息，是因为 系统用户目录下缺少 .cloudmusic 目录，手动创建一个就可以使用了。当然了我是看到无法打开 .cloudmusic/err.log 文件创建了这一个文件。

**Comment by YXL76** [comment]
确实是我的失误，请尝试`v8.2.2` @WuLiangXiaoSeng ，不过原issue是在老版本提出的，应该是另外的问题

**Comment by YXL76** [comment]
@lilirg @SanQiG 你们大概可以正常使用`v8.2.2`

**Comment by L2Fish** [comment]
我也遇到了这个问题，看了 @WuLiangXiaoSeng 的回答后，尝试更换了管理员身份运行vscode。
之后这个问题被解决了，并且后续无序管理员身份运行。
