### ISSUE TITLE
希望歌单列表添加一个双击播放或者右键播放，加入快捷键会更好。

### ISSUE THREAD

**Issue by manson-2020** [YXL76/cloudmusic-vscode#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by manson-2020** [comment]
歌单列表里面的播放按钮开始找半天没找到， 结果是侧边栏空间小了挡住了

**Comment by YXL76** [comment]
双击播放应该不能实现，因为`vscode`并没有相关API，快捷键的话所有命令都可以设置。 @manson-2020

**Comment by manson-2020** [comment]
![image](https://user-images.githubusercontent.com/43368308/93545668-91cf1d80-f993-11ea-9aad-393569141929.png)
就像这种的右键菜单新增一个播放可以实现吗

**Comment by YXL76** [comment]
可以 @manson-2020

**Comment by YXL76** [comment]
`v4.6.3`中添加了上下文菜单@manson-2020
