### ISSUE TITLE
8.0以上的版本不能扫码登录

### ISSUE THREAD

**Issue by zhr85210078** [YXL76/cloudmusic-vscode#436]
8.0以上的版本不能扫码登录，退回到7.7.2可以扫码登录

**Comment by YXL76** [comment]
我这边可以使用，能试试最新的8.2.2m吗

**Comment by YXL76** [comment]
错误信息
- `Help->Toggle Developer Tools->Console`（帮助->切换开发者工具->控制台）
- `%homepath%/.cloudmusic/err.log`

**Comment by sky5454** [comment]
安卓 v8.2.10 扫码登录正常
