### ISSUE TITLE
在Archlinux上Code和Visual Studio Code都无法登录

### ISSUE THREAD

**Issue by Ylin97** [YXL76/cloudmusic-vscode#439]
# Describe the issue
v8.2.4版在Archlinux中邮箱、手机和二维码三种方式都登录不上去，当输入帐号和密码或扫描二维码确定后，页面会刷新一下，但没有登录成功且没有任何错误信息。经测试在windows上一切正常。   
![](https://pic.imgdb.cn/item/60a396806ae4f77d35184945.gif)  
# OS and vscode information
系统信息：   
OS: Arch Linux x86_64  
Kernel: 5.12.4-arch1-2   
DE: Plasma 5.21.5

Visual Studio Code版本：1.56.2

**Comment by YXL76** [comment]
查看`~/.cloudmusic/err.log`

**Comment by LiangYalin** [comment]
> 查看`~/.cloudmusic/err.log`

最新版输出如下：
```
1621328328863 [Error: ENOENT: no such file or directory, open '/home/yalin/.cloudmusic/cache/music-list'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/yalin/.cloudmusic/cache/music-list'
}
1621329338999 Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by YXL76** [comment]
使用环境有设置`http_proxy`环境变量吗

**Comment by LiangYalin** [comment]
> 使用环境有设置`http_proxy`环境变量吗

没有设置。另外，我上午在Manjora里面尝试了一下，发现Manjora里面一切正常。   
然后我又回到Archlinux，但问题依旧，~/.cloudmusic/err.log的记录和上面的一样。

**Comment by YXL76** [comment]
大概和什么发行版无关，因为开发就是在Arch Linux上进行的。
现在对这个错误没什么想法。

**Comment by GGshawn** [comment]
> # Describe the issue
> v8.2.4版在Archlinux中邮箱、手机和二维码三种方式都登录不上去，当输入帐号和密码或扫描二维码确定后，页面会刷新一下，但没有登录成功且没有任何错误信息。经测试在windows上一切正常。
> ![](https://camo.githubusercontent.com/a9d5b27cc81f20a6e52fb1b74df7daad438b727c5999990d9930ea4704fb6f94/68747470733a2f2f7069632e696d6764622e636e2f6974656d2f3630613339363830366165346637376433353138343934352e676966)
> 
> # OS and vscode information
> 系统信息：
> OS: Arch Linux x86_64
> Kernel: 5.12.4-arch1-2
> DE: Plasma 5.21.5
> 
> Visual Studio Code版本：1.56.2

插件版本试一下7.2.0

**Comment by YXL76** [comment]
请检查`v9.0.0`

**Comment by Ylin97** [comment]
> 请检查`v9.0.0`

**Comment by ADSWT518** [comment]
> 使用环境有设置`http_proxy`环境变量吗

请问设置了此环境变量会有什么影响？我在尝试二维码登录的时候，发现点击之后没有反应。密码登录也显示登录失败。

`~/.cloudmusic/err.log` 内容如下：

```
1628229221229 Error: Request failed with status code 400
    at ns.exports (/home/adswt518/.vscode/extensions/yxl.cloudmusic-9.1.3/dist/server.js:1:5090)
    at os.exports (/home/adswt518/.vscode/extensions/yxl.cloudmusic-9.1.3/dist/server.js:1:5262)
    at IncomingMessage.<anonymous> (/home/adswt518/.vscode/extensions/yxl.cloudmusic-9.1.3/dist/server.js:6:12135)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

插件版本：最新版（9.1.3）
操作系统： Arch Linux
KDE Plasma 版本： 5.22.4
KDE 框架版本： 5.84.0
内核版本： 5.13.8-arch1-1 (64-位)

谢谢您

**Comment by YXL76** [comment]
Linux 独有的吗？Windows 下的结果呢？

**Comment by YXL76** [comment]
> > 使用环境有设置`http_proxy`环境变量吗
> 
> 请问设置了此环境变量会有什么影响？我在尝试二维码登录的时候，发现点击之后没有反应。密码登录也显示登录失败。
> 
> `~/.cloudmusic/err.log` 内容如下：
> 
> ```
> 1628229221229 Error: Request failed with status code 400
>     at ns.exports (/home/adswt518/.vscode/extensions/yxl.cloudmusic-9.1.3/dist/server.js:1:5090)
>     at os.exports (/home/adswt518/.vscode/extensions/yxl.cloudmusic-9.1.3/dist/server.js:1:5262)
>     at IncomingMessage.<anonymous> (/home/adswt518/.vscode/extensions/yxl.cloudmusic-9.1.3/dist/server.js:6:12135)
>     at IncomingMessage.emit (events.js:327:22)
>     at endReadableNT (internal/streams/readable.js:1327:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)
> ```
> 
> 插件版本：最新版（9.1.3）
> 操作系统： Arch Linux
> KDE Plasma 版本： 5.22.4
> KDE 框架版本： 5.84.0
> 内核版本： 5.13.8-arch1-1 (64-位)
> 
> 谢谢您

Linux 独有的吗？Windows 下的结果呢？

**Comment by ADSWT518** [comment]
> > > 使用环境有设置`http_proxy`环境变量吗
> > 
> > 
> > 请问设置了此环境变量会有什么影响？我在尝试二维码登录的时候，发现点击之后没有反应。密码登录也显示登录失败。
> > `~/.cloudmusic/err.log` 内容如下：
> > ```
> > 1628229221229 Error: Request failed with status code 400
> >     at ns.exports (/home/adswt518/.vscode/extensions/yxl.cloudmusic-9.1.3/dist/server.js:1:5090)
> >     at os.exports (/home/adswt518/.vscode/extensions/yxl.cloudmusic-9.1.3/dist/server.js:1:5262)
> >     at IncomingMessage.<anonymous> (/home/adswt518/.vscode/extensions/yxl.cloudmusic-9.1.3/dist/server.js:6:12135)
> >     at IncomingMessage.emit (events.js:327:22)
> >     at endReadableNT (internal/streams/readable.js:1327:12)
> >     at processTicksAndRejections (internal/process/task_queues.js:80:21)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 插件版本：最新版（9.1.3）
> > 操作系统： Arch Linux
> > KDE Plasma 版本： 5.22.4
> > KDE 框架版本： 5.84.0
> > 内核版本： 5.13.8-arch1-1 (64-位)
> > 谢谢您
> 
> Linux 独有的吗？Windows 下的结果呢？

经过简单的测试（在Windows下也加入http_proxy等环境变量），发现了一模一样的问题，`err.log`中的信息也一模一样。

**Comment by YXL76** [comment]
> > Linux 独有的吗？Windows 下的结果呢？
> 
> 经过简单的测试（在Windows下也加入http_proxy等环境变量），发现了一模一样的问题，`err.log`中的信息也一模一样。

开个新 Issue 吧。重新描述一下，`http_proxy` 就不要管了。

**Comment by ADSWT518** [comment]
> > > Linux 独有的吗？Windows 下的结果呢？
> > 
> > 
> > 经过简单的测试（在Windows下也加入http_proxy等环境变量），发现了一模一样的问题，`err.log`中的信息也一模一样。
> 
> 开个新 Issue 吧。重新描述一下，`http_proxy` 就不要管了。

但是在Windows上没设置`http_proxy`的时候是可以正常登录的 :rofl: 所以我感觉是不是就是这个问题呢？

**Comment by YXL76** [comment]
最好在vscode里设置`http.proxy`
