### ISSUE TITLE
在播放音乐的时候,能明显的在Deepin任务管理器内看到 VSC的URL Handler进程占用运存比网易云音乐Linux版本还要高

### ISSUE THREAD

**Issue by 8MiYile** [YXL76/cloudmusic-vscode#454]
**Describe the bug**
在播放音乐的时候,能明显的在Deepin任务管理器内看到 VSC的URL Handler进程占用运存比网易云音乐Linux版本还要高

**Error information (Help->Toggle Developer Tools->Console)**
```
1622215585616 [Error: ENOENT: no such file or directory, open '/home/bmi_yile/.cloudmusic/cache/music-list'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/bmi_yile/.cloudmusic/cache/music-list'
}
1622215664300 502
1622216028196 TypeError: Cannot read property 'map' of undefined
    at Tr (/home/bmi_yile/.vscode-insiders/extensions/yxl.cloudmusic-8.3.4/dist/server.js:8:21773)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function._handler (/home/bmi_yile/.vscode-insiders/extensions/yxl.cloudmusic-8.3.4/dist/server.js:9:8235)
1622216028714 TypeError: Cannot read property 'map' of undefined
    at Tr (/home/bmi_yile/.vscode-insiders/extensions/yxl.cloudmusic-8.3.4/dist/server.js:8:21773)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function._handler (/home/bmi_yile/.vscode-insiders/extensions/yxl.cloudmusic-8.3.4/dist/server.js:9:8235)

```

**Environment (Help->About)**
```
版本: 1.57.0-insider
提交: 4fd4e10e99eff9eb77408b71c7f58b7ed7458ee5
日期: 2021-05-21T05:13:19.775Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.29-amd64-desktop
```

**ScreenShot**
![QQ截图20210529001505](https://user-images.githubusercontent.com/25455400/120013710-ac25c480-c013-11eb-80f8-984215a4515c.png)

**Comment by YXL76** [comment]
具体占用高的进程是什么呢？以及详细的堆栈情况

**Comment by 8MiYile** [comment]
@YXL76 你好,从图示中可以看出 进程全被URL Handler包起来了...
堆栈情况嘛, 我找找

**Comment by YXL76** [comment]
1. 一开始的图里不是有好几个进程，你觉得内存占用高的，他的`Command`是什么呢？
2. Deepin任务管理器不能看堆栈吗？

**Comment by YXL76** [comment]
对于之后的那张图，减去共享内存后，占用大概40M。检查这部分的堆栈信息，看是否有异常。

**Comment by 8MiYile** [comment]
/usr/share/code-insiders/code-insiders --type=gpu-process --field-trial-handle=762539481107742802,8352651600326463621,131072 --enable-features=WebComponentsV0Enabled --disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --disable-color-correct-rendering --enable-crash-reporter=45564c7b-becb-4703-bcf5-1a44ce095f42,no_channel --global-crash-keys=45564c7b-becb-4703-bcf5-1a44ce095f42,no_channel,_companyName=Microsoft,_productName=VSCode,_version=1.57.0-insider --gpu-preferences=UAAAAAAAAAAgAAAQAAAAAAAAAAAAAAAAAABgAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAA= --shared-files

**Comment by YXL76** [comment]
不激活本插件，正常coding时的占用情况又是什么呢？

**Comment by 8MiYile** [comment]
等会 难道VSCode本身加载就这么大吗?
![1](https://user-images.githubusercontent.com/25455400/120061899-efbf1380-c091-11eb-94ac-38e768e1ba9e.png)

**Comment by 8MiYile** [comment]
那没事了 和这插件无关 是我乌龙了
