### ISSUE TITLE
命令窗口增加键盘来选择歌曲以及控制后退

### ISSUE THREAD

**Issue by hzfmer** [YXL76/cloudmusic-vscode#455]
**Is your feature request related to a problem? Please describe.**
在调出搜索弹窗之后，一般用上下箭头+ Enter 可以一步一步向下操作，但最后无法用键盘选中。比如account-search-歌曲名字-单曲 （Search 4/4），
![image](https://user-images.githubusercontent.com/28425640/120048412-e8cdcd80-bfcb-11eb-9707-0a1190b683c9.png)

在这个地方，怎么选中这首歌，比如进入详情，或者类似鼠标勾中然后点 OK （也许是我没看到怎么操作，如果没有的话，希望可以支持）？

以及，之后可能想回到“歌曲名字”，也就是回到 “search 3/4”， 而不是从头开始一遍：
![image](https://user-images.githubusercontent.com/28425640/120048479-1286f480-bfcc-11eb-9e97-f73286000e41.png)

**Describe the solution you'd like**
考虑 “Enter" 表示 “OK” （Shift + Enter 进入详情？），“Space”支持多选。
考虑“backspace”可以向上跳一层，最后回到 account 1/4。

谢谢！

**Comment by YXL76** [comment]
1. 多选列表。`Space`选择，`Alt+Enter`表示OK
2. 按钮的快捷键在`tooltip`里会显示，后退的应该是`Ctrl+Alt+-`

**Comment by hzfmer** [comment]
确实是有的，只是我没找到这些 shortcut。
谢谢！
