### ISSUE TITLE
暂停/播放时渐入渐出

### ISSUE THREAD

**Issue by Chlorie** [YXL76/cloudmusic-vscode#46]
如标题所述，现在播放和暂停的时候非常突然。如果可以实现的话能不能在播放和暂停的时候留出大概 0.5s 的时间将音量逐渐过渡到目标值？

**Comment by YXL76** [comment]
确实是个很有用的功能，不过目前在进行5.0.0的开发，等到下次重构本机模块的时候再看看怎么实现吧。
