### ISSUE TITLE
搜索结果/PLAYLIST都无法添加到queue

### ISSUE THREAD

**Issue by YXL76** [YXL76/cloudmusic-vscode#465]
@hzfmer

> **Describe the bug**
> 无法添加到queue： Cannot read property 'itemType' of null
> 
> **Error information (Help->Toggle Developer Tools->Console)**
> 
> ```
> workbench.desktop.main.js:2237 [[object Object]]Cannot read property 'itemType' of null
> $onExtensionRuntimeError @ workbench.desktop.main.js:2237
> _doInvokeHandler @ workbench.desktop.main.js:1770
> _invokeHandler @ workbench.desktop.main.js:1770
> _receiveRequest @ workbench.desktop.main.js:1770
> _receiveOneMessage @ workbench.desktop.main.js:1770
> (anonymous) @ workbench.desktop.main.js:1770
> fire @ workbench.desktop.main.js:60
> fire @ workbench.desktop.main.js:76
> _receiveMessage @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> fire @ workbench.desktop.main.js:60
> acceptChunk @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> _ @ workbench.desktop.main.js:2710
> emit @ events.js:315
> addChunk @ internal/streams/readable.js:309
> readableAddChunk @ internal/streams/readable.js:284
> Readable.push @ internal/streams/readable.js:223
> onStreamRead @ internal/stream_base_commons.js:188
> workbench.desktop.main.js:2237 TypeError: Cannot read property 'itemType' of null
> 	at Function._parseRaw (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45)
> 	at ~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45
> 	at Array.map (<anonymous>)
> 	at Function._add (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45)
> 	at Function.add (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45)
> 	at hr (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:77)
> 	at Socket.<anonymous> (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45)
> 	at Socket.emit (events.js:315)
> 	at addChunk (internal/streams/readable.js:309)
> 	at readableAddChunk (internal/streams/readable.js:280)
> 	at Socket.Readable.push (internal/streams/readable.js:223)
> 	at Pipe.onStreamRead (internal/stream_base_commons.js:188)
> $onExtensionRuntimeError @ workbench.desktop.main.js:2237
> _doInvokeHandler @ workbench.desktop.main.js:1770
> _invokeHandler @ workbench.desktop.main.js:1770
> _receiveRequest @ workbench.desktop.main.js:1770
> _receiveOneMessage @ workbench.desktop.main.js:1770
> (anonymous) @ workbench.desktop.main.js:1770
> fire @ workbench.desktop.main.js:60
> fire @ workbench.desktop.main.js:76
> _receiveMessage @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> fire @ workbench.desktop.main.js:60
> acceptChunk @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> _ @ workbench.desktop.main.js:2710
> emit @ events.js:315
> addChunk @ internal/streams/readable.js:309
> readableAddChunk @ internal/streams/readable.js:284
> Readable.push @ internal/streams/readable.js:223
> onStreamRead @ internal/stream_base_commons.js:188
> DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/054a9295330880ed74ceaedda236253b4f39a335/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
> workbench.desktop.main.js:2237 [[object Object]]Cannot read property 'itemType' of null
> $onExtensionRuntimeError @ workbench.desktop.main.js:2237
> _doInvokeHandler @ workbench.desktop.main.js:1770
> _invokeHandler @ workbench.desktop.main.js:1770
> _receiveRequest @ workbench.desktop.main.js:1770
> _receiveOneMessage @ workbench.desktop.main.js:1770
> (anonymous) @ workbench.desktop.main.js:1770
> fire @ workbench.desktop.main.js:60
> fire @ workbench.desktop.main.js:76
> _receiveMessage @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> fire @ workbench.desktop.main.js:60
> acceptChunk @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> _ @ workbench.desktop.main.js:2710
> emit @ events.js:315
> addChunk @ internal/streams/readable.js:309
> readableAddChunk @ internal/streams/readable.js:284
> Readable.push @ internal/streams/readable.js:223
> onStreamRead @ internal/stream_base_commons.js:188
> workbench.desktop.main.js:2237 TypeError: Cannot read property 'itemType' of null
> 	at Function._parseRaw (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45)
> 	at ~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45
> 	at Array.map (<anonymous>)
> 	at Function._add (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45)
> 	at Function.add (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45)
> 	at hr (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:77)
> 	at Socket.<anonymous> (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45)
> 	at Socket.emit (events.js:315)
> 	at addChunk (internal/streams/readable.js:309)
> 	at readableAddChunk (internal/streams/readable.js:280)
> 	at Socket.Readable.push (internal/streams/readable.js:223)
> 	at Pipe.onStreamRead (internal/stream_base_commons.js:188)
> $onExtensionRuntimeError @ workbench.desktop.main.js:2237
> _doInvokeHandler @ workbench.desktop.main.js:1770
> _invokeHandler @ workbench.desktop.main.js:1770
> _receiveRequest @ workbench.desktop.main.js:1770
> _receiveOneMessage @ workbench.desktop.main.js:1770
> (anonymous) @ workbench.desktop.main.js:1770
> fire @ workbench.desktop.main.js:60
> fire @ workbench.desktop.main.js:76
> _receiveMessage @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> fire @ workbench.desktop.main.js:60
> acceptChunk @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> _ @ workbench.desktop.main.js:2710
> emit @ events.js:315
> addChunk @ internal/streams/readable.js:309
> readableAddChunk @ internal/streams/readable.js:284
> Readable.push @ internal/streams/readable.js:223
> onStreamRead @ internal/stream_base_commons.js:188
> workbench.desktop.main.js:2237 [[object Object]]Cannot read property 'itemType' of null
> $onExtensionRuntimeError @ workbench.desktop.main.js:2237
> _doInvokeHandler @ workbench.desktop.main.js:1770
> _invokeHandler @ workbench.desktop.main.js:1770
> _receiveRequest @ workbench.desktop.main.js:1770
> _receiveOneMessage @ workbench.desktop.main.js:1770
> (anonymous) @ workbench.desktop.main.js:1770
> fire @ workbench.desktop.main.js:60
> fire @ workbench.desktop.main.js:76
> _receiveMessage @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> fire @ workbench.desktop.main.js:60
> acceptChunk @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> _ @ workbench.desktop.main.js:2710
> emit @ events.js:315
> addChunk @ internal/streams/readable.js:309
> readableAddChunk @ internal/streams/readable.js:284
> Readable.push @ internal/streams/readable.js:223
> onStreamRead @ internal/stream_base_commons.js:188
> workbench.desktop.main.js:2237 TypeError: Cannot read property 'itemType' of null
> 	at Function._parseRaw (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45)
> 	at ~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45
> 	at Array.map (<anonymous>)
> 	at Function._add (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45)
> 	at Function.add (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45)
> 	at hr (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:77)
> 	at Socket.<anonymous> (~/.vscode/extensions/yxl.cloudmusic-8.3.4/dist/extension.js:45)
> 	at Socket.emit (events.js:315)
> 	at addChunk (internal/streams/readable.js:309)
> 	at readableAddChunk (internal/streams/readable.js:280)
> 	at Socket.Readable.push (internal/streams/readable.js:223)
> 	at Pipe.onStreamRead (internal/stream_base_commons.js:188)
> $onExtensionRuntimeError @ workbench.desktop.main.js:2237
> _doInvokeHandler @ workbench.desktop.main.js:1770
> _invokeHandler @ workbench.desktop.main.js:1770
> _receiveRequest @ workbench.desktop.main.js:1770
> _receiveOneMessage @ workbench.desktop.main.js:1770
> (anonymous) @ workbench.desktop.main.js:1770
> fire @ workbench.desktop.main.js:60
> fire @ workbench.desktop.main.js:76
> _receiveMessage @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> fire @ workbench.desktop.main.js:60
> acceptChunk @ workbench.desktop.main.js:76
> (anonymous) @ workbench.desktop.main.js:76
> _ @ workbench.desktop.main.js:2710
> emit @ events.js:315
> addChunk @ internal/streams/readable.js:309
> readableAddChunk @ internal/streams/readable.js:284
> Readable.push @ internal/streams/readable.js:223
> onStreamRead @ internal/stream_base_commons.js:188
> ```
> 
> **Environment (Help->About)**
> Paste the content in `Help->About`
> 粘贴`帮助->关于`中的内容
> Version: 1.56.2
> Commit: 054a9295330880ed74ceaedda236253b4f39a335
> Date: 2021-05-12T17:44:30.902Z (3 wks ago)
> Electron: 12.0.4
> Chrome: 89.0.4389.114
> Node.js: 14.16.0
> V8: 8.9.255.24-electron.0
> OS: Darwin x64 18.7.0

**Comment by YXL76** [comment]
请检查`v8.3.5` @hzfmer

**Comment by hzfmer** [comment]
目前看起来没有问题，谢谢 @YXL76 !
