### ISSUE TITLE
远程连接时无法添加本地主机上的音乐

### ISSUE THREAD

**Issue by NAIXIL** [YXL76/cloudmusic-vscode#470]
当我的windows下的vscode连接远程linux（Remote-SSH）的时候，无法读取本地windows的本地文件。不进行远程连接的时候可以读取添加本地文件夹。
vscode版本：1.56.2

**Comment by YXL76** [comment]
是指添加`Local library`吗？

**Comment by NAIXIL** [comment]
是的。

**Comment by NAIXIL** [comment]
虽然不能在连接远程linux主机的时候添加windows本地文件夹，但是能先不连接远程主机然后在本地添加windows的文件夹之后，再重启vscode就可以在连接上远程主机之后看到添加的windows的音乐文件夹了。

**Comment by YXL76** [comment]
`v8.3.5`中已修复
