### ISSUE TITLE
播放设备问题

### ISSUE THREAD

**Issue by sensty** [YXL76/cloudmusic-vscode#492]
在播放过程中切换了播放设备（比如有扬声器切换到耳机）音频不能立刻切换，要在下一曲时才能切换过去。

**Comment by YXL76** [comment]
需要系统信息

**Comment by Youmiel** [comment]
Windows 10 20H1, 遇到同样的问题，情况是连接了外置声卡，但是音乐播放没有随系统声音那样切换到声卡设备上，也是切换曲目之后才行。可以确定我没有调整过VSC单独的声音选项。
