### ISSUE TITLE
希望可以统一一下图标，符合客户端使用习惯

### ISSUE THREAD

**Issue by cnsdwu** [YXL76/cloudmusic-vscode#496]
比如官方喜欢用心形图标，收藏用星形图标
而且有发现一处不合理，状态栏的喜欢用的是星，而歌曲详情时用的是心
![image](https://user-images.githubusercontent.com/23513790/124548551-7967bb00-de60-11eb-80e2-0a405dccf473.png)
![image](https://user-images.githubusercontent.com/23513790/124548610-87b5d700-de60-11eb-81e3-d69938a1dae7.png)

**Comment by YXL76** [comment]
选用星是因为它有空和满的区分

**Comment by YXL76** [comment]
在`v9.0.0`中修改
