### ISSUE TITLE
我的mac上激活失败

### ISSUE THREAD

**Issue by webxmsj** [YXL76/cloudmusic-vscode#5]
版本: 1.47.2
提交: 17299e413d5590b14ab0340ea477cdd86ff13daf
日期: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

![image](https://user-images.githubusercontent.com/40289489/88001712-5bac2380-cb33-11ea-99e4-7622560a2f01.png)

**Comment by YXL76** [comment]
[test.zip](https://github.com/YXL76/cloudmusic-vscode/files/4950951/test.zip)

请你尝试在终端运行以上程序，并把输出发给我。 @webxmsj

**Comment by YXL76** [comment]
[#398](https://github.com/RustAudio/cpal/issues/398)

**Comment by YXL76** [comment]
[RustAudio/cpal#398](https://github.com/RustAudio/cpal/issues/398)，等待上游修复

**Comment by YXL76** [comment]
请更新至`3.4.0`，检查插件是否可用。 @webxmsj

**Comment by webxmsj** [comment]
![image](https://user-images.githubusercontent.com/40289489/88764590-ca2e5880-d1a7-11ea-9994-5bc63176ca23.png)
激活成功了， 但是点击bo播放还是有报错

**Comment by YXL76** [comment]
请检查`v3.7.4` @webxmsj

**Comment by webxmsj** [comment]
可以了 👍
