### ISSUE TITLE
如何播放日推

### ISSUE THREAD

**Issue by taooceros** [YXL76/cloudmusic-vscode#50]
**Describe the problem you encountered.**
A clear and concise description of what the question is.

问下如何播放日推的歌单，因为我看api似乎是支持的

**Comment by YXL76** [comment]
登录后点击状态栏的帐号图标 @taooceros

**Comment by taooceros** [comment]
o看到了，但是如果添加整个歌单到列表里呢？

**Comment by YXL76** [comment]
还没有这个功能，我最近加一下吧 @taooceros

**Comment by taooceros** [comment]
好的好的，谢谢！

**Comment by YXL76** [comment]
`4.6.2`应该就可以添加整个歌单了@taooceros

**Comment by taooceros** [comment]
nice, 谢谢！

**Comment by taooceros** [comment]
呃兄弟……似乎那个按钮只被加到了歌单里，日推里面没有呀😂

**Comment by YXL76** [comment]
`v4.6.3`添加了单曲多选功能@taooceros
