### ISSUE TITLE
Majaro使用最新版本无法登录，使用7.1.0可以登录

### ISSUE THREAD

**Issue by GGshawn** [YXL76/cloudmusic-vscode#502]
由于一直扫码导致帐号异常，最后使用7.1.0，通过手机号登录成功

**Comment by GGshawn** [comment]
可以的登录成功的最新版本是7.2.0,尝试过程中发现一个规律，如果是右下角vscode弹出的sign in提示，这个版本就可以登录成功，但如果是单独的alert,问是否allow,这样的版本就无法登录，有的会说sign in failed,有的就什么也不提示

**Comment by YXL76** [comment]
请问`VS Code`是从`AUR`安装的吗？

**Comment by GGshawn** [comment]
> 请问`VS Code`是从`AUR`安装的吗？

解压的

**Comment by YXL76** [comment]
请检查`v9.0.0`
