### ISSUE TITLE
进入扩展导致扩展宿主意外终止

### ISSUE THREAD

**Issue by UID163844189** [YXL76/cloudmusic-vscode#503]
在侧边栏点击扩展图标或者在命令面板输入命令的时候，会显示“扩展宿主意外终止。”
![2021-07-09-144453_1920x1080_scrot](https://user-images.githubusercontent.com/53218742/125038351-e466fb00-e0c7-11eb-98ba-2d867456e2d1.png)
![2021-07-09-145416_1920x1080_scrot](https://user-images.githubusercontent.com/53218742/125038349-e3ce6480-e0c7-11eb-97ca-7d5a78062af5.png)
![2021-07-09-145854_1920x1080_scrot](https://user-images.githubusercontent.com/53218742/125038352-e466fb00-e0c7-11eb-954f-0902cce28d19.png)

版本: 1.57.1
提交: 507ce72a4466fbb27b715c3722558bb15afa9f48
日期: 2021-06-17T13:26:13.866Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux arm 5.10.17-v7+

**Comment by YXL76** [comment]
注意看[Requirements](https://github.com/YXL76/cloudmusic-vscode/blob/master/README.md#requirements)，现在不支持`Linux arm`。下一个`Major`版本会支持。

**Comment by YXL76** [comment]
请检查`v9.0.0`
