### ISSUE TITLE
能否记住上次的播放队列

### ISSUE THREAD

**Issue by alienzhangyw** [YXL76/cloudmusic-vscode#507]
**Is your feature request related to a problem? Please describe.**
目前插件每次启动时，队列会自动清空并加载每日推荐歌曲。使用起来很不方便，每次都要手动搜索歌曲或把歌单添加到队列。
而且插件启动时会自动开始播放队列中的推荐歌曲，有时候会造成困扰。

**Describe the solution you'd like**
队列记住之前播放的内容，不自动清空并加载推荐歌曲，或者提供设置选项。

**Describe alternatives you've considered**
使用网易云的历史记录接口，或者使用外部文件记录队列历史。

**Comment by YXL76** [comment]
`v9.1.0`添加了`cloudmusic.queue.initialization`设置项
