### ISSUE TITLE
播放无声音

### ISSUE THREAD

**Issue by Ylin97** [YXL76/cloudmusic-vscode#518]
**Describe the bug**
v9.0.1 点击歌曲的播放按钮后无声音，但歌词能够正常滚动。查看 ~/.cloudmusic/cache 目录后发现存在对应歌曲的音频缓存，且能够用其他播放器播放。

**Error information**  
控制台没有信息输出。  

**Server logs**  
```
ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
```   
**Environment**
> 版本: 1.58.2
> 提交: c3f126316369cd610563c75b1b1725e0679adfb3
> 日期: 2021-07-14T22:30:16.440Z
> Electron: 12.0.13
> Chrome: 89.0.4389.128
> Node.js: 14.16.0
> V8: 8.9.255.25-electron.0
> OS: Linux x64 5.13.7-arch1-1

**Comment by YXL76** [comment]
设置一下音量有用吗？

**Comment by YXL76** [comment]
安装`pulseaudio-alsa`后呢？

**Comment by Ylin97** [comment]
安装pulseaudio-alsa后正常了，十分感谢。

兰陈昕 ***@***.***> 于2021年8月2日周一 下午6:11写道：
