### ISSUE TITLE
无法喜欢歌曲

### ISSUE THREAD

**Issue by Purotis** [YXL76/cloudmusic-vscode#521]
#### 点击 歌曲菜单的喜欢 或 红心 后会显示两个一样的用户，无论点哪个都提示取消喜欢
![capture_20210803211747213](https://user-images.githubusercontent.com/39762924/128023490-cb5192f1-4654-49cd-bff4-31dff7689c0b.png)

- vsc: 1.58.2
- cloudmusic: 9.1.1

**Comment by YXL76** [comment]
在`v9.1.2`中修复
