### ISSUE TITLE
喜欢按钮

### ISSUE THREAD

**Issue by cheng-shuai** [YXL76/cloudmusic-vscode#528]
**Describe the problem you encountered.**
A clear and concise description of what the question is.
清楚简洁地说明问题。
以前点击喜欢按钮可以直接喜欢，现在点击喜欢要打开选择。而且喜欢的音乐按钮没有加黑
![image](https://user-images.githubusercontent.com/60097799/128586252-26e33268-7f8f-4d43-9649-b353fce82a84.png)

**Comment by YXL76** [comment]
归到 #525

**Comment by YXL76** [comment]
在`v9.2.0`中会检查目前喜欢的状态
