### ISSUE TITLE
扩展宿主意外终止

### ISSUE THREAD

**Issue by degawong** [YXL76/cloudmusic-vscode#536]
**Describe the bug**
扩展宿主意外终止

**Error information**
![{bfeb6848-04cb-4090-9776-a4e27e8018ec}](https://user-images.githubusercontent.com/18233018/131646963-79ce4844-283e-4b8c-88d5-ace31acfa79d.png)

**Server logs**
文件夹为空，安装之后点击按钮右下角就返回`扩展宿主意外终止`

**Environment**
![{f8d95f5a-033f-45a5-b141-1f85d9d04836}](https://user-images.githubusercontent.com/18233018/131647139-98a9166e-585a-4fae-9c7d-16a1987bfb09.png)

**Comment by degawong** [comment]
#503 是`linux arm`，此`issue`在`windows`平台

**Comment by YXL76** [comment]
尝试关闭`regex workbench`？

**Comment by YXL76** [comment]
我看到不少类似的问题：[regexworkbench#14](https://github.com/stephen-riley/regexworkbench/issues/14)、[regexworkbench#15](https://github.com/stephen-riley/regexworkbench/issues/15)

**Comment by degawong** [comment]
谢谢 @YXL76 ，我把`regex workbench`禁用之后，可以正常使用了，希望有时间可以解决下这个问题，谢谢你的贡献

**Comment by yume-chan** [comment]
See stephen-riley/pcre2-wasm#3

是 Emscripten 默认会捕获同进程里的 uncaughtException 和 unhandledRejection 然后 crash 进程。

https://github.com/YXL76/cloudmusic-vscode/blob/244e34a830437c98894748c284ef9f7768dfda17/packages/client/src/utils/ipc.ts#L79-L90

可能是这里 socket 的 error 没捕获，触发了 uncaughtException

**Comment by YXL76** [comment]
在`v9.2.4`中修复
