### ISSUE TITLE
状态栏显示建议

### ISSUE THREAD

**Issue by yume-chan** [YXL76/cloudmusic-vscode#549]
## 1. 现在的问题

1. `cloudmusic.toggleButton` 显示 undefined，且歌名和歌词选项的会显示当前的歌名和歌词，看起有点奇怪

    ![image](https://user-images.githubusercontent.com/1330321/133581452-034f5374-d3eb-4717-afb0-26231360844b.png)

    Upstream issue: microsoft/vscode#133231

2. `"cloudmusic.statusBar.compact": true` 时 `cloudmusic.toggleButton` 无效
3. 修改 tooltip 内容时 tooltip 会自动隐藏

    Upstream issue: microsoft/vscode#128887

## 2. 提案

1. 删除 `cloudmusic.statusBar.compact` 选项
2. 每个按钮有三种状态，分别为“显示”，“隐藏”和“收起”，所有“收起”的项目会显示在第一个“显示”的按钮的 tooltip 里

    我觉得可以把这些状态都改为设置，例如 `cloudmusic.statusBar.songName`, `cloudmusic.statusBar.playPause` 等，不用代码做 picker 切换，用户修改和设置同步都会更方便（也就是说删除 `cloudmusic.toggleButton` command 或者改为跳转到设置编辑器）

    例如：设置“上一曲”为收起，设置“暂停”为隐藏，则“上一曲”显示在“下一曲”的 tooltip 里，而暂停按钮不显示
3. 将部分点击歌名后的操作移动到歌名的 tooltip 里，包括专辑，艺术家，复制链接，下载，并且可以点击（tooltip 里也可以显示图片，如果需要的话可以显示专辑封面）
4. 如果歌名按钮的状态是“隐藏”，将以上信息+歌名移动到第一个显示的按钮的 tooltip 里
5. 以上的显示应该也可以扩展到播放列表的歌曲 tooltip 里

显示效果 mock

1. tooltip 里显示其它“收起”的按钮

    ```text
    [$(chevron-left)](command:cloudmusic.previous) | [$(chevron-right)](command:cloudmusic.next)
    ```

2. 歌名按钮的 tooltip + 其它“收起”的按钮，或者其它按钮 tooltip 显示“收起”状态的歌名

    ```text
    $(circuit-board) [专辑名称](command:cloudmusic.pickAlbum?albumId]
    $(account) [艺术家1](command:cloudmusic.pickArtist?artistId1) / [艺术家2](command:cloudmusic.pickArtist?artistId2)
    $(cloud-download) [下载](command:downloadSong?songId)
    ---
    [$(chevron-left)](command:cloudmusic.previous) | [$(chevron-right)](command:cloudmusic.next)
    ```

**Comment by YXL76** [comment]
挺好。

> 第一个“显示”的按钮

不如就放在歌名的按钮。`tooltip`里应该没有减少空间的需求，状态就只分隐藏和显示。简单来说就是只改歌名按钮的`tooltip`为一个完成的面板

**Comment by yume-chan** [comment]
> `tooltip` 里应该没有减少空间的需求，状态就只分隐藏和显示

我一开始想的是保留已有的自定义功能，不过确实 tooltip 里多显示几个感觉也没有问题

> 不如就放在歌名的按钮

我之前怕歌名的 tooltip 会太大，而且歌名也可以被隐藏

**Comment by yume-chan** [comment]
主 po 的两个 issue 在 insiders 里都修复了，不过开启 compact 后歌名的 tooltip 还是不对

![image](https://user-images.githubusercontent.com/1330321/133868041-e939edd0-d051-489d-bea8-1de688af9112.png)

**Comment by YXL76** [comment]
等待上游：[vscode#109025](https://github.com/microsoft/vscode/issues/109025)，[vscode#133123](https://github.com/microsoft/vscode/issues/133123)

**Comment by YXL76** [comment]
请检查`v9.4.0`
