### ISSUE TITLE
无法播放歌曲 log报错无法找到模块

### ISSUE THREAD

**Issue by sck0537** [YXL76/cloudmusic-vscode#564]
**Describe the bug**
无法播放歌曲 log报错
**Error information**
![image](https://user-images.githubusercontent.com/61313985/136016807-8709774d-f11d-4a1f-9977-3e41f68ff1f1.png)
**Server logs**
![image](https://user-images.githubusercontent.com/61313985/136016705-6bd0e8c3-7011-431b-bb2e-2b69e14e6500.png)
- Linux/MacOS: `~/.cloudmusic/err-<version>.log`
- Windows: `%homepath%/.cloudmusic/err-<version>.log`

**Environment**
![image](https://user-images.githubusercontent.com/61313985/136016950-1d4ed369-32ab-4d54-a1ed-fe8da61e5503.png)

**Comment by eo2pd** [comment]
把play mode改成wasm就好了
