### ISSUE TITLE
无法使用私人FM

### ISSUE THREAD

**Issue by Cao0220** [YXL76/cloudmusic-vscode#565]
![image](https://user-images.githubusercontent.com/65110919/136377283-03005dff-ef6b-4b9d-ae7f-6ad4c96fa298.png)
当我如图点击私人FM时，一直跳到账号，无法播放

**Comment by YXL76** [comment]
有什么错误信息吗？

**Comment by Canoming** [comment]
不知道是什么问题。 我发现必须要先从 playlist 里面播放音乐，然后才能加载出私人 FM

**Comment by YXL76** [comment]
`v9.7.0` 中修复了部分问题
