### ISSUE TITLE
能否添加 播放速度 切换的功能.

### ISSUE THREAD

**Issue by TvsAECC** [YXL76/cloudmusic-vscode#576]
**Is your feature request related to a problem? Please describe.**
我在摸鱼的时候经常听点电台和广播剧(也就是播单功能).习惯听电台使用x1.5倍速或者x2倍速.
有时候也会下载一些电台音频到本地使用您的插件在vscode 里边摸鱼边工作.

**Describe the solution you'd like**
希望在播放控制栏添加一个倍速切换的功能.比如现有音量控制那样,可以预设几个速度也可以由用户填速度值.

**Comment by YXL76** [comment]
`v9.7.0` 支持调节播放速度，但是不会影响正在播放的文件

**Comment by YXL76** [comment]
改变速度不改变音高可能需要使用 `FFT` 之类的算法，我对音频处理没有什么经验

**Comment by YXL76** [comment]
`v9.8.2` 中可在播放时调整速度
