### ISSUE TITLE
支持操作系统的媒体控制

### ISSUE THREAD

**Issue by frg2089** [YXL76/cloudmusic-vscode#591]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
> 清楚简洁地说明问题所在。例如，当[...]时，我总是感到沮丧。

当我不能在Windows 11的Action Center里控制播放器时, 我总是感到沮丧  
当我不能在锁屏界面上控制播放器时, 我总是感到沮丧

> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 简洁明了地描述您想要的功能。

我希望我可以在Windows 11的Action Center和锁屏界面中看到当前播放的歌曲和控制播放器

> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 对您考虑过的所有解决方案或功能的简洁明了的描述。

### 在Action Center中可以
- [x] 能够显示歌曲的名称 歌手等内容
- [x] 点击播放按钮时可以播放
- [x] 点击暂停按钮时可以暂停
- [x] 点击上一曲按钮时可以切换到上一首歌
- [x] 点击下一曲按钮时可以切换到下一首歌

### 在锁屏界面中可以
- [x] 能够显示歌曲的名称 歌手等内容
- [x] 点击播放按钮时可以播放
- [x] 点击暂停按钮时可以暂停
- [x] 点击上一曲按钮时可以切换到上一首歌
- [x] 点击下一曲按钮时可以切换到下一首歌

### 在Action Center中可以
- [ ] 能够显示歌曲的名称 歌手等内容
- [ ] 点击播放按钮时可以播放
- [ ] 点击暂停按钮时可以暂停
- [ ] 点击上一曲按钮时可以切换到上一首歌
- [ ] 点击下一曲按钮时可以切换到下一首歌

### 在锁屏界面中可以
- [ ] 能够显示歌曲的名称 歌手等内容
- [ ] 点击播放按钮时可以播放
- [ ] 点击暂停按钮时可以暂停
- [ ] 点击上一曲按钮时可以切换到上一首歌
- [ ] 点击下一曲按钮时可以切换到下一首歌

> **Additional context**
> Add any other context or screenshots about the feature request here.
> 在此处添加有关功能请求的其他任何内容或屏幕截图。

(cloudmusic扩展工作时的)Windows 11的Action Center的部分截图
![image](https://user-images.githubusercontent.com/42184238/139540749-526b83cd-f7c8-4896-8a9f-70bf4debf478.png)

(Groove 音乐工作时的)Windows 11 Action Center部分截图
![image](https://user-images.githubusercontent.com/42184238/139541500-50f77b41-2f46-4cfd-970b-54f77d9cc126.png)

(Groove 音乐工作时的)Windows 11锁屏界面右下角部分截图
![image](https://user-images.githubusercontent.com/42184238/139541320-522e8c5b-dfce-45c6-a2d1-e197ae6ff56f.png)

**Comment by YXL76** [comment]
看起来最新的VS Code构建已经不能播放大部分音频了，只能等待[WebCodecs](https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API)成为稳定特性。
临时的解决方法是[替换libffmpeg](https://github.com/nondanee/vsc-netease-music#requirement)

**Comment by Chinesezjc** [comment]
所以说现在大部分音频都无法播放吗，本机 Ubuntu 20.04 无法播放 _Magic∞world_

**Comment by YXL76** [comment]
> 所以说现在大部分音频都无法播放吗，本机 Ubuntu 20.04 无法播放 _Magic∞world_

与音乐播放功能无关，这里讨论的是`MediaSession`API，Magic∞world你在手机上可以播放吗？

**Comment by Chinesezjc** [comment]
> > 所以说现在大部分音频都无法播放吗，本机 Ubuntu 20.04 无法播放 _Magic∞world_
> 
> 与音乐播放功能无关，这里讨论的是`MediaSession`API，Magic∞world你在手机上可以播放吗？

并不能，它是黑胶会员专享，但是同为黑胶会员专享的_No buts!_可以正常播放。

**Comment by YXL76** [comment]
> > > 所以说现在大部分音频都无法播放吗，本机 Ubuntu 20.04 无法播放 _Magic∞world_
> > 
> > 
> > 与音乐播放功能无关，这里讨论的是`MediaSession`API，Magic∞world你在手机上可以播放吗？
> 
> 并不能，它是黑胶会员专享，但是同为黑胶会员专享的_No buts!_可以正常播放。

手机客户端播不了的话，本插件应该也不行

**Comment by Chinesezjc** [comment]
> > > > 所以说现在大部分音频都无法播放吗，本机 Ubuntu 20.04 无法播放 _Magic∞world_
> > > 
> > > 
> > > 与音乐播放功能无关，这里讨论的是`MediaSession`API，Magic∞world你在手机上可以播放吗？
> > 
> > 
> > 并不能，它是黑胶会员专享，但是同为黑胶会员专享的_No buts!_可以正常播放。
> 
> 手机客户端播不了的话，本插件应该也不行

可是部分手机客户端播放不了的音乐在本插件下可以播放。

**Comment by yume-chan** [comment]
Related to microsoft/vscode#118275

实在不行就只能在 Rust 里实现每个系统的播放控制集成？

Windows 有 `windows` crate https://microsoft.github.io/windows-docs-rs/doc/windows/Media/struct.SystemMediaTransportControls.html

macOS 要用 `MPNowPlayingInfoCenter` https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter ，似乎没有现成的 Rust binding

Linux 有 `mpris-player` https://lib.rs/crates/mpris-player 和 `mpris` https://lib.rs/crates/mpris 两个 crate

**Comment by YXL76** [comment]
> Relates to [microsoft/vscode#118275](https://github.com/microsoft/vscode/issues/118275)
> 
> 实在不行就只能在 Rust 里实现每个系统的播放控制集成？
> 
> Windows 有 `windows` crate https://microsoft.github.io/windows-docs-rs/doc/windows/Media/struct.SystemMediaTransportControls.html
> 
> macOS 要用 `MPNowPlayingInfoCenter` https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter ，似乎没有现成的 Rust binding
> 
> Linux 有 `mpris-player` https://lib.rs/crates/mpris-player 和 `mpris` https://lib.rs/crates/mpris 两个 crate
> 
> EDIT: 可以参考 Chrome 的相关代码 https://source.chromium.org/chromium/chromium/src/+/main:components/system_media_controls/

为了适配 Web extension，已经决定完全分离 Native 和 Wasm，所以接下来确实要在 Rust 中实现媒体控制，而且有 [sinono3/souvlaki](https://github.com/sinono3/souvlaki) 可以直接使用

**Comment by YXL76** [comment]
请尝试 `v9.6.1`

**Comment by frg2089** [comment]
> 请尝试 `v9.6.1`

我刚刚试过后发现...活动中心中的暂停按钮似乎存在问题  
- ❓音乐正在播放时 活动中心并没有显示暂停按钮
- ✔️当音乐暂停时 活动中心的继续播放按钮正常工作
- ✔️活动中心的上一曲按钮正常工作
- ✔️活动中心的下一曲按钮正常工作

---
VSCode中状态栏与活动中心按钮显示不同
![VSCode中状态栏与活动中心按钮显示不同](https://user-images.githubusercontent.com/42184238/149304300-988c591f-8fc0-40c6-a90f-bb5b2e32842d.png)

**Comment by yume-chan** [comment]
在 macOS 12.1 上完全没有显示正在播放信息

**Comment by yume-chan** [comment]
我试了下 souvlaki 的 example，macOS 必须要有窗口才能显示正在播放（例如 winit 的 EventLoop）。问题是虽然窗口不可见，但是会在 Dock 上显示一个图标。

winit 没提供隐藏 Dock 图标的接口，所以没法测试没有图标的应用是否可以作为正在播放应用。

**Comment by yume-chan** [comment]
另外现在是否完全不依赖 Account view 里的 webview 了？可否将 activition events 设置为 *，使插件可以在隐藏边栏的情况下自动启动？

**Comment by frg2089** [comment]
> 在 macOS 12.1 上完全没有显示正在播放信息

我认为这个可以另写一个新的issue
或者我改一下标题...?

**Comment by YXL76** [comment]
应该是没有设置播放状态的问题

**Comment by YXL76** [comment]
> 另外现在是否完全不依赖 Account view 里的 webview 了？可否将 activition events 设置为 *，使插件可以在隐藏边栏的情况下自动启动？

应该是可以的，不过自动启动好像有些人不太喜欢

**Comment by YXL76** [comment]
我想 `v9.6.2` 应该能解决之前提到的问题

**Comment by YXL76** [comment]
@yume-chan `winit`提供了在 Mac OS 下隐藏应用的接口，见
https://github.com/rust-windowing/winit/blob/11a44081df97b82108be63a925d8c479bddfdc4d/src/platform/macos.rs#L235
因为文档是在 Linux 下构建的所以没有条目，所以你可以尝试一下

**Comment by yume-chan** [comment]
https://github.com/rust-windowing/winit/blob/11a44081df97b82108be63a925d8c479bddfdc4d/src/platform_impl/macos/app_delegate.rs#L60

Command+H 类似于 Windows 的最小化，要改的是这里的 `activation_policy`

**Comment by yume-chan** [comment]
> 我认为这个可以另写一个新的issue

现在是用一个库同时支持 Windows Linux 和 macOS，就都在这里反馈了

**Comment by yume-chan** [comment]
https://gist.github.com/yume-chan/d739eeff13ecc660b72772675a32bdb2

这是基于 souvlaki 的 example 修改的在 macOS 上最小可运行的例子

有个问题：`EventLoop` 必须在 main thread 上创建，且必须 `run` 起来，但是这个方法不会返回，和 Node.js 的 libuv event loop 冲突。

一种解决方案是在 `run` 里手动调用 libuv 的 `uv_run` 维持 Node.js 运行，类似一些同步执行 Promise 的方案：

```c
uv_run(node::GetCurrentEventLoop(v8::Isolate::GetCurrent()), UV_RUN_ONCE);
```

https://github.com/abbr/deasync/blob/50cc7daba1edd6be77d1b7e0bc297933fefbd1f2/src/deasync.cc#L10

`MediaControls` 也需要在 main thread 上创建和操作，不过如果像上面那样，那 JS 调用的时候就是在 main thread 上，可以不考虑

**Comment by YXL76** [comment]
@yume-chan `EventLoop` 可以使用类似于 `poll` 的方式运行，见 [EventLoopExtRunReturn](https://docs.rs/winit/latest/x86_64-apple-darwin/winit/platform/run_return/trait.EventLoopExtRunReturn.html)，可以尝试一下。以及想问一下编译目标是 `aarch64`？

**Comment by yume-chan** [comment]
> 设置 `*control_flow = ControlFlow::Exit;` 后回到主线程还能不能保持媒体控制存在

不能

> 以及想问一下编译目标是 aarch64？

`stable-x86_64-apple-darwin`

**Comment by YXL76** [comment]
看起来返回前调用了 `stop`，用 `setImmediate` 轮询可能成本太高了。使用 `uv_run` 的坏处是，[`neon`](https://github.com/neon-bindings/neon) 目前拿不到 `event_loop_s`，可能要转用 [`napi-rs`](https://github.com/napi-rs/napi-rs)

https://github.com/rust-windowing/winit/blob/cf4660841a35139f4b48ac71f6c7cd9482ab5198/src/platform_impl/macos/app_state.rs#L424

```rust
                autoreleasepool(|| {
                    if !INTERRUPT_EVENT_LOOP_EXIT.load(Ordering::SeqCst)
                        && !dialog_open
                        && !dialog_is_closing
                    {
                        let () = msg_send![app, stop: nil];
                        // To stop event loop immediately, we need to post some event here.
                        post_dummy_event(app);
                    }
                });
```

**Comment by yume-chan** [comment]
应该是 macOS 的 `NSApp run` 本身就是阻塞的，`stop` 只是发个 event 让 `run` 退出

我在 Google 的时候看到可以用 https://developer.apple.com/documentation/appkit/nsapplication/1428485-nexteventmatchingmask?language=objc 来 pull event，但是没看到具体的例子。

不管怎么样，两个 event loop 必须要 pull 一个，我觉得都不是很好的方案

**Comment by YXL76** [comment]
> 另外现在是否完全不依赖 Account view 里的 webview 了？可否将 activition events 设置为 *，使插件可以在隐藏边栏的情况下自动启动？

`v9.7.0` 中添加了 `cloudmusic.host.autoStart` 设置项，开启后自动激活插件

**Comment by YXL76** [comment]
我觉得比较简单的方法还是再开一个进程，也连接服务器的 Socket

**Comment by YXL76** [comment]
我在 `v9.10.0` 里添加了 mac 的支持，但是没办法测试
