### ISSUE TITLE
状态栏的专辑图片太大了

### ISSUE THREAD

**Issue by CHminggao** [YXL76/cloudmusic-vscode#593]
**Is your feature request related to a problem? Please describe.**
状态栏鼠标移到歌曲那里就会显示歌曲的图片（专辑图片？）功能还是挺好的
但是有的歌的**图片太大了**，鼠标不小心放过去直接整个vscode的界面都挡住了（下图，有的还会更大

**Describe the solution you'd like**
**可不可以把图片大小固定了**

![image](https://user-images.githubusercontent.com/28477604/139641443-a48cfbe4-d499-415f-adab-cbd54d332f26.png)

**Comment by YXL76** [comment]
同 #549

**Comment by YXL76** [comment]
在`v9.4.0`中解决
