### ISSUE TITLE
“私人FM”使用异常

### ISSUE THREAD

**Issue by 5ME** [YXL76/cloudmusic-vscode#598]
每次新打开VS Code后，点击”私人FM“没有反应，把网易云账号退出再登录就好了，不知道什么原因。

我使用的是扫码登录。

我一般早上打开VS Code后一天都不会关，所以这个问题对我来说每天只有一次，但也有点烦人，希望能早点修复。

辛苦啦！

**Comment by YXL76** [comment]
暂时不能复现

**Comment by YXL76** [comment]
请检查`v9.5.0`
