### ISSUE TITLE
建议状态栏[歌词]增加可隐藏。只显示控制按钮

### ISSUE THREAD

**Issue by heartacker** [YXL76/cloudmusic-vscode#6]
rt，
希望只显示控制按钮，不显示歌词，因为闪来闪去感觉有点晃眼。影响coding 💯

**Comment by YXL76** [comment]
> rt，
> 希望只显示控制按钮，不显示歌词，因为闪来闪去感觉有点晃眼。影响coding

有类似想法，预计将在下一个版本实现

**Comment by YXL76** [comment]
已在`3.2.0`中添加`Cloudmusic: Toggle button`命令
