### ISSUE TITLE
在编辑器中显示歌词时会同时出现两行完全一样的歌词

### ISSUE THREAD

**Issue by topbardon** [YXL76/cloudmusic-vscode#625]
**Describe the problem you encountered.**
A clear and concise description of what the question is.
清楚简洁地说明问题。
在编辑器中显示歌词时会同时出现两行完全一样的歌词
<img width="684" alt="image" src="https://user-images.githubusercontent.com/95011132/147799474-77308aa3-0d26-4ced-9fbd-0febe93e2405.png">

**Comment by topbardon** [comment]
希望能像网易云等流媒体服务一样，在编辑器中显示两行以上的、即将播放的歌词。不然在编辑器中显示歌词就会和启用Lyric的功能重复了。

**Comment by YXL76** [comment]
`v9.6.0` 已支持
