### ISSUE TITLE
最近的更新导致 cloudmusic 行为很奇怪, 无法正常播放

### ISSUE THREAD

**Issue by liaohongxing** [YXL76/cloudmusic-vscode#631]
**Describe the problem you encountered.**
A clear and concise description of what the question is.
清楚简洁地说明问题。
1. 最近更新导致本地曲库增加了 cache\music 怎么也删不掉。不是我想要的。
2. 最近更新导致播放排行榜或者单曲播放 ，不是立即播放，播放的内容也不知道是哪里的,具体看图

我进行了 卸载重装 ，退出再登陆 ，都一样的问题 。

**Comment by liaohongxing** [comment]
![x](https://user-images.githubusercontent.com/35255844/150477846-66840ca9-9124-4ae7-8dae-7ec5ed46010f.gif)

**Comment by SoYoungHa** [comment]
一样的问题

**Comment by YXL76** [comment]
从 `v9.7.0` 开始吗？是否有错误信息：

- 帮助->切换开发者工具->控制台
- Linux/MacOS: `~/.cloudmusic/err-<version>.log`
- Windows: `%homepath%/.cloudmusic/err-<version>.log`

**Comment by liaohongxing** [comment]
1. 日志文件是空的，
2. 升级到 v9.8.0 已恢复正常, 原因暂时未明 。
3. 既然歌曲用歌名+ids, 建议歌词也用 歌名+ids , 还有那个 tmp 目录里的文件也是这样命名 ，方便找文件。找歌词

**Comment by alienzhangyw** [comment]
同样的问题，点击播放歌曲没反应，状态栏也没有当前歌曲，需要重启vscode多次才能正常播放。
