### ISSUE TITLE
在code-server中无法播放

### ISSUE THREAD

**Issue by feilongproject** [YXL76/cloudmusic-vscode#641]
**Describe the bug**
在播放歌曲时，除歌曲的播放链接外，其余功能正常

**Error information**
![image](https://user-images.githubusercontent.com/43880786/155752544-3ea8730f-d615-414b-af44-b77bcb825adc.png)

**Server logs**

```
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
```

**Environment**
code-server
版本: 1.63.0
提交: 5cdfe74686aa73e023f8354a9a6014eb30caa7dd
日期: 2022-01-27T22:22:39Z (4 周前)
浏览器: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.56
系统: Ubuntu 20.04.3 LTS
安装方式: vsix
服务器已开启https

**Comment by YXL76** [comment]
请切换到`wasm`模式
