### ISSUE TITLE
音乐搜索

### ISSUE THREAD

**Issue by PIndividual** [YXL76/cloudmusic-vscode#644]
**Is your feature request related to a problem? Please describe.**
虽然简介里面已经说明了搜索功能的支持，但我还是无法找到相应的指令或窗口
**Describe the solution you'd like**
添加独立的搜索区域
**Describe alternatives you've considered**
或许在侧边栏里面添加一个搜索结果会好点，或者更新一下支持的指令？

**Additional context**
在此处添加有关功能请求的其他任何内容或屏幕截图。

**Comment by YXL76** [comment]
点击用户头像可打开搜索

**Comment by PIndividual** [comment]
试了一下，输入完歌名按enter除了搜索框消失以外没别的反应了啊

**Comment by YXL76** [comment]
出来的`QuickPick`中有一个搜索选项，点进去再输入

**Comment by PIndividual** [comment]
我试了下，输入完需要的内容按enter啥反应也没有

**Comment by YXL76** [comment]
请检查 `v9.9.0`
