### ISSUE TITLE
维持登录状态

### ISSUE THREAD

**Issue by WinstonMeursault** [YXL76/cloudmusic-vscode#651]
请问这个插件可以维持登录状态吗？
为什么我在每次打开VS Code后都需要重新登录账号？

**Comment by YXL76** [comment]
请问是用什么登录方式？

日志：
- Linux/MacOS: `~/.cloudmusic/err-<version>.log`
- Windows: `%homepath%/.cloudmusic/err-<version>.log`

**Comment by WinstonMeursault** [comment]
用过验证码，也用过手机号
重新加载窗口可以维持登录，但关掉VSC再重新打开就不行了

那个日志是空的（捂脸）

**Comment by YXL76** [comment]
密码登录也是一样吗

**Comment by YXL76** [comment]
看看控制台有什么信息（`Help->Toggle Developer Tools->Console`），感觉是 Storage 有问题

**Comment by WinstonMeursault** [comment]
检索"music"信息里只有一条"[Extension Host] Cloudmusic: native mode."
检索不到含"Storage"的信息

**Comment by YXL76** [comment]
在 `v9.8.4` 中有变化吗

**Comment by tylvn** [comment]
> 在 `v9.8.4` 中有变化吗

刚试的时候可以维持登录状态，过了一段时间后再试就发现不能了😂

**Comment by FrankShepard** [comment]
账户密码登录不了，是因为使用网页版本需要手动校验的原因吗？目前只能使用二维码登录，且保持时间不确定

**Comment by YXL76** [comment]
> 账户密码登录不了，是因为使用网页版本需要手动校验的原因吗？目前只能使用二维码登录，且保持时间不确定

如果显示“验证码错误”就是了

**Comment by allinprogram** [comment]
对于该问题，可以考虑使用cookie进行登陆控制，其失效期最短为15天。

**Comment by YXL76** [comment]
请检查`v9.13.0`

**Comment by WinstonMeursault** [comment]
好的谢谢

发件人: 兰陈昕
发送时间: 2022年8月7日 16:14
收件人: YXL76/cloudmusic-vscode
抄送: Winston Meursault; Author
主题: Re: [YXL76/cloudmusic-vscode] 维持登录状态 (Issue #651)

请检查v9.13.0

**Comment by WinstonMeursault** [comment]
我刚才试了一下,  没有问题了
重启VSCode后可以保持登录状态
感谢Thanks♪(･ω･)ﾉ
