### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by chaoshengt** [YXL76/cloudmusic-vscode#659]
错误信息：
`
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
`

log文件中的信息：
1648977499415 参数错误
1648977754001 参数错误
(node:19244) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Code --trace-deprecation ...` to show where the warning was created)
1648978037736 参数错误
1648978070271 参数错误
1648978086476 验证码错误
1648978098983 验证码错误
1648978110530 验证码错误
(node:17044) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Code --trace-deprecation ...` to show where the warning was created)
1649033457732 参数错误
1649033533593 验证码错误
1649033543859 验证码错误
1649033634127 验证码错误
(node:4112) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Code --trace-deprecation ...` to show where the warning was created)

**Comment by YXL76** [comment]
二维码登录呢？

**Comment by chaoshengt** [comment]
> 二维码登录呢？

用网易云音乐的二维码扫描登陆，没问题，可以成功。
奇怪，之前我记得，是可以在vscode中用邮箱登陆成功的，后来更新vscode，重新登陆失败，就再也无法登陆成功了。

**Comment by pluveto** [comment]
二维码登录点了没有任何反应

**Comment by YXL76** [comment]
如果 `v9.8.4` 还是不行，可以尝试在设置中关闭 HTTPS 和 SSL
