### ISSUE TITLE
能添加 VPN or proxy 翻墙回国内吗

### ISSUE THREAD

**Issue by gray4what** [YXL76/cloudmusic-vscode#662]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
清楚简洁地说明问题所在。例如，当[...]时，我总是感到沮丧。

**Describe the solution you'd like**
简洁明了地描述您想要的功能。

**Describe alternatives you've considered**
对您考虑过的所有解决方案或功能的简洁明了的描述。

**Additional context**
在此处添加有关功能请求的其他任何内容或屏幕截图。

**Comment by YXL76** [comment]
直接用代理软件不行吗？
