### ISSUE TITLE
Activating extension 'YXL.cloudmusic' failed

### ISSUE THREAD

**Issue by daocheburuku** [YXL76/cloudmusic-vscode#663]
workbench.desktop.main.js:2615 Activating extension 'YXL.cloudmusic' failed: Unable to resolve nonexistent file 'c:\Users\XXX \.vscode\extensions\yxl.cloudmusic-9.8.3-win32-ia32\build'.

![WeChat Image_20220409093946](https://user-images.githubusercontent.com/42764429/162551592-30cb3ab0-9993-42fb-826e-969eb523f4ac.png)

**Comment by YXL76** [comment]
目前没有 32 位 Windows 的预构建，可以先使用 wasm 模式

**Comment by daocheburuku** [comment]
谢谢
