### ISSUE TITLE
在开启ssl的情况下code-server不能播放

### ISSUE THREAD

**Issue by Lianting-Wang** [YXL76/cloudmusic-vscode#665]
**Describe the bug**
在开启ssl的情况下code-server可以登录并正常显示歌单，但无法播放。
<img width="491" alt="Screen Shot 2022-04-11 at 12 55 47 AM" src="https://user-images.githubusercontent.com/53719791/162667519-8212555d-3d5b-40b3-b352-f7b1c569fe05.png">

经过测试发现本地曲库中的文件在更改了后缀以后可以在电脑上正常播放。
<img width="240" alt="Screen Shot 2022-04-11 at 1 25 40 AM" src="https://user-images.githubusercontent.com/53719791/162670365-021f2258-ff22-4530-8565-d8158e2ced09.png">

**Error information**
<img width="1023" alt="Screen Shot 2022-04-11 at 12 52 20 AM" src="https://user-images.githubusercontent.com/53719791/162667155-7163d091-286c-4634-a5f3-4069ba27961b.png">

**Server logs**
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/souvlaki-0.5.1/src/platform/linux/mod.rs:182:29
1649652846110 Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: SendError { .. }
    at Function.load (/config/extensions/yxl.cloudmusic-9.8.3/dist/server.js:15:5286)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Environment**
Code - OSS
版本: 1.64.2
提交: Unknown
日期: 2022-03-22T20:16:06.512Z (2 周前)
浏览器: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36

**Comment by YXL76** [comment]
同 #660
