### ISSUE TITLE
插件一直在加载，无法正常使用任何命令

### ISSUE THREAD

**Issue by SongshGeo** [YXL76/cloudmusic-vscode#669]
**Describe the bug**
一直在加载插件，使用插件命令报错：
![CleanShot2022-04-23at09.16.52](https://songshgeo-picgo-1302043007.cos.ap-beijing.myqcloud.com/uPic/CleanShot%202022-04-23%20at%2009.16.52.png)

顺利登陆过用了很久（和其它issue类似，能用二维码登陆，不能用别的方式）。昨天晚上忽然不能正常用了，试过重装插件，没有解决。

**Error information**
![CleanShot2022-04-23at09.07.51](https://songshgeo-picgo-1302043007.cos.ap-beijing.myqcloud.com/uPic/CleanShot%202022-04-23%20at%2009.07.51.png)
控制台没有过滤到 cloudmusic 相关的很多记录：
![CleanShot2022-04-23at09.15.25](https://songshgeo-picgo-1302043007.cos.ap-beijing.myqcloud.com/uPic/CleanShot%202022-04-23%20at%2009.15.25.png)

**Server logs**
- Linux/MacOS: `~/.cloudmusic/err-<version>.log`

```
(node:47428) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
1650589076572 验证码错误
1650589106289 验证码错误
(node:75991) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
(node:72676) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
(node:8888) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `Electron --trace-deprecation ...` to show where the warning was created)
```

**Environment**
```

版本: 1.66.2
提交: dfd34e8260c270da74b5c2d86d61aee4b6d56977
日期: 2022-04-11T07:49:20.994Z (1 周前)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.4.0
```

另，请问大佬这个仓库 commit message 的 emoji 是用什么实现的呀！好有趣

**Comment by YXL76** [comment]
> 另，请问大佬这个仓库 commit message 的 emoji 是用什么实现的呀！好有趣

有这些插件可以用：[Conventional Commits](https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits)、[git-commit-plugin](https://marketplace.visualstudio.com/items?itemName=redjue.git-commit-plugin)

**Comment by SongshGeo** [comment]
感谢 hhh！我去玩一玩

> > 另，请问大佬这个仓库 commit message 的 emoji 是用什么实现的呀！好有趣
> 
> 有这些插件可以用：[Conventional Commits](https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits)、[git-commit-plugin](https://marketplace.visualstudio.com/items?itemName=redjue.git-commit-plugin)

**Comment by YXL76** [comment]
如果 `v9.8.4` 还是不行，可以尝试在设置中关闭 HTTPS 和 SSL

**Comment by SongshGeo** [comment]
刚试了一下，关了这两个，我没理解错吧：
![CleanShot2022-04-24at18.18.54](https://songshgeo-picgo-1302043007.cos.ap-beijing.myqcloud.com/uPic/CleanShot%202022-04-24%20at%2018.18.54.png)

也重启了再试，还是不行。版本确认了是 `v9.8.4`。

**Comment by VoltaDusk** [comment]
![1651156577(1)](https://user-images.githubusercontent.com/42726833/165777345-20206d95-7dd0-4893-b8ab-212ec34716d5.jpg)
同样的问题，关闭Api的 HTTPS 后可以登录了

**Comment by YXL76** [comment]
请检查 `v9.9.0` 是否可以使用

**Comment by SongshGeo** [comment]
`v9.9.1` 可以啦
