### ISSUE TITLE
添加云盘相关的支持

### ISSUE THREAD

**Issue by ericzhao007** [YXL76/cloudmusic-vscode#694]
在mac系统中的网易云音乐不支持上传到云盘，是否可以考虑在 [cloudmusic-vscode](https://github.com/YXL76/cloudmusic-vscode)中添加此项支持。

**Comment by lulu-ls** [comment]
这个项目可以帮助你在 mac 上传音乐：[cloud-uploader](https://github.com/lulu-ls/cloud-uploader)
