### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by vincenteliang** [YXL76/cloudmusic-vscode#7]
执行登录命令后弹出以下提示：

命令"Cloudmusic: Sign in"导致错误 （command 'cloudmusic.signin' not found）

插件版本：3.2.1
VScode版本：1.47.2
系统：macOS 10.15.5

**Comment by YXL76** [comment]
请检查Help->Toggle Developer Tools，在执行命令之前是否有其他错误信息。 @vincenteliang
