### ISSUE TITLE
Mac下无法使用

### ISSUE THREAD

**Issue by CN-Haoling** [YXL76/cloudmusic-vscode#701]
**Describe the bug**
未知依赖问题导致无法使用，表现为点击入插件后账号条持续加载

**Error information**
![image](https://user-images.githubusercontent.com/61273411/170883786-5ec8f84d-45dc-448a-8f1b-a21ae6d7cdf9.png)

**Server logs**
查看了log信息为空

**Environment**
版本: 1.65.2
提交: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
日期: 2022-03-10T14:42:05.236Z (2 个月前)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

**Comment by YXL76** [comment]
目前新版需要 Node16，可以选择升级 vscode

**Comment by CN-Haoling** [comment]
好的感谢
