### ISSUE TITLE
在哪里开启status bar歌词显示

### ISSUE THREAD

**Issue by potuo** [YXL76/cloudmusic-vscode#702]
在哪里开启status bar歌词显示

**Comment by YXL76** [comment]
![image](https://user-images.githubusercontent.com/43405544/170930416-5a6a5e93-64fc-49ee-a729-31bd6d23bc06.png)

**Comment by potuo** [comment]
> ![图片](https://user-images.githubusercontent.com/43405544/170930416-5a6a5e93-64fc-49ee-a729-31bd6d23bc06.png)

已解决，谢谢
