### ISSUE TITLE
怎么登陆？

### ISSUE THREAD

**Issue by hub607** [YXL76/cloudmusic-vscode#721]
我在账号栏点击登录  
先尝试了二维码 点了后就结束了 没有任何消息
然后尝试了 手机号   到输入完密码后敲回车没有任何反应
![image](https://user-images.githubusercontent.com/38717760/173781566-cc6fc4f7-ba6a-4b0f-8bd5-1d7552a96fba.png)
又尝试了验证码 也是一样的问题
大佬们 是我使用的方法不对嘛

**Comment by 645418484** [comment]
![image](https://user-images.githubusercontent.com/38717760/173784211-1acfc850-bbc9-4fba-bcb0-6b36cb3b7a92.png)

**Comment by 645418484** [comment]
路径为啥会多个D:\  = =

**Comment by YXL76** [comment]
已在 `v9.10.4` 中修复

**Comment by faimin** [comment]
好像并没有修复。我用的 v9.10.5 版本，选择邮箱登录，输入密码后回车，依然没有任何反应

**Comment by YXL76** [comment]
> 好像并没有修复。我用的 `v9.10.5` 版本，选择邮箱登录，输入密码后回车，依然没有任何反应

请用二维码
