### ISSUE TITLE
希望能支持代理

### ISSUE THREAD

**Issue by Lisu-Liso** [YXL76/cloudmusic-vscode#747]
之前用不了这个扩展，一直用的是VSC-NeateaseMusic，现在又能用了，发现太强大了。
但是不支持设置代理！（那个也不支持）这我很郁闷，我收藏的好多歌都是用UnblockedNeteaseMusic的，所以好多没版权，都听不了。希望能设置代理

**Comment by YXL76** [comment]
目前支持 `htyp.proxy` 设置

**Comment by NESGUIAM** [comment]
![image](https://user-images.githubusercontent.com/99577760/178213727-e88a05ee-a91d-48fc-919d-b32d67f73b98.png)
是这个吗

**Comment by YXL76** [comment]
对

**Comment by NESGUIAM** [comment]
设置好后可以播放音乐但是还是看不到没有版权的歌曲

**Comment by NESGUIAM** [comment]
不知道是不是没有重启VSCode的原因

**Comment by YXL76** [comment]
应该是把无法播放的歌曲过滤了。

之前的版本有集成 UnblockedNeteaseMusic，但因为维护问题移除了。多平台的支持在计划中但一直没有时间写。

**Comment by NESGUIAM** [comment]
能不能更新下独立使用代理，其他VSCode中有网络访问的扩展不能正常使用了

**Comment by NESGUIAM** [comment]
会提示加载Web视图时出错，应该是最新版本的UnblockedNeteaseMusic不能访问那么多乱七八糟的

**Comment by YXL76** [comment]
`v9.11.0` 中添加了 `cloudmusic.network.proxy` 选项

**Comment by NESGUIAM** [comment]
好的，蟹蟹

**Comment by NESGUIAM** [comment]
咳咳....新的问题：
"cloudmusic.network.proxy": "http://127.0.0.1:6666",
这么设置对吗，应该是对的，可以播放音乐（未缓存），但是没有版权的音乐还是放不了....
哦哦，对不起忘记了是http
但是
![image](https://user-images.githubusercontent.com/99577760/178420714-06bcfc08-80ea-4e7a-8c5b-8ad2b2945320.png)
这个...看起来很别扭，而且我喜欢列表里还是没有这首音乐希望修一下，比如没版权的音乐加个'*'，开代理了就不管这样的
蟹蟹

**Comment by NESGUIAM** [comment]
![image](https://user-images.githubusercontent.com/99577760/178421119-0ad9a48e-adcd-4fd1-93a0-0764e6e95a63.png)
非常好，取消了之后就回不去了。（官方能喜欢，不知道为什么）

**Comment by YXL76** [comment]
> ![image](https://user-images.githubusercontent.com/99577760/178421119-0ad9a48e-adcd-4fd1-93a0-0764e6e95a63.png)
> 非常好，取消了之后就回不去了。（官方能喜欢，不知道为什么）

是不是已经在列表里了

**Comment by NESGUIAM** [comment]
![image](https://user-images.githubusercontent.com/99577760/178421599-90523ce0-c46a-4c09-a794-7576ebd13b4c.png)
没有...

**Comment by YXL76** [comment]
> ![image](https://user-images.githubusercontent.com/99577760/178421599-90523ce0-c46a-4c09-a794-7576ebd13b4c.png)
> 没有...

手机里看得到吗

**Comment by NESGUIAM** [comment]
![image](https://user-images.githubusercontent.com/99577760/178421828-22adc7b5-bc0f-4c66-9cd4-d9e171e6d0e9.png)

**Comment by NESGUIAM** [comment]
这是刚加的

**Comment by NESGUIAM** [comment]
不知道是不是UnblockedNeteaseMusic的问题，网易云里版本不太一样...

**Comment by NESGUIAM** [comment]
噢噢噢噢，两个版本是一样的，都不是原唱...

**Comment by NESGUIAM** [comment]
现在代理能用了，就是有点歌单显示的问题，还有添加喜欢也稍微有点问题

**Comment by NESGUIAM** [comment]
嗯，还是我，发现不能登录了，能不能把登录单独不使用代理啊蟹蟹蟹蟹

**Comment by YXL76** [comment]
日志:

- Linux/MacOS: `~/.cloudmusic/err-<version>.log`
- Windows: `%homepath%/.cloudmusic/err-<version>.log`

**Comment by NESGUIAM** [comment]
![image](https://user-images.githubusercontent.com/99577760/178487224-0b294cc3-443e-49e9-a4f7-5ab7e4f07ed2.png)

**Comment by NESGUIAM** [comment]
耐心等待ing~

**Comment by NESGUIAM** [comment]
重新安装扩展还是没有用

**Comment by YXL76** [comment]
是否修改缓存路径？日志在这个目录下。

开发者工具的日志（`Help->Toggle Developer Tools->Console`）

**Comment by NESGUIAM** [comment]
现在在日照，不在家里，不太方便，还有5天差不多就回去了，回头再说吧
