### ISSUE TITLE
记住密码功能

### ISSUE THREAD

**Issue by lvlouhs** [YXL76/cloudmusic-vscode#777]
登录状态不易维持，经常重新加载窗口就会注销，能不能加个记住密码的功能？至少不用每次都输入一遍手机号/邮箱和密码了

**Comment by YXL76** [comment]
一直都有记住密码。重新加载窗口是指 reload 吗？理论上不会掉登录。

**Comment by lvlouhs** [comment]
原来是这样吗，那会不会是因为我日常挂着梯子的原因呢，需要设为海外用户吗？reload的时候不怎么会掉登录，关掉重开经常会掉。

**Comment by YXL76** [comment]
我看下有没有 bug 吧

**Comment by YXL76** [comment]
请检查`v9.13.0`
