### ISSUE TITLE
账户登陆长时间卡住

### ISSUE THREAD

**Issue by zhucj1981** [YXL76/cloudmusic-vscode#779]
不知道是什么情况，登陆的进度条一直在滚动。
插件卸载重装后还是一样
<img width="446" alt="image" src="https://user-images.githubusercontent.com/49010201/183242789-c45dcdaa-f615-48e5-9164-2a95a16fd48b.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/49010201/183242967-84d71948-6505-4fbe-8b4f-cb0d02747046.png">

**Comment by YXL76** [comment]
需要日志

**Comment by zhucj1981** [comment]
请问日志在哪里查看？

**Comment by YXL76** [comment]
**Error information**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`.
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容。

**Server logs**
Execute `cloudmusic.openLogFile`.
执行 `cloudmusic.openLogFile`。

**Comment by zhucj1981** [comment]
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/49010201/183246417-237376d9-f658-43f4-bc4d-cfed5426832c.png">
<img width="270" alt="image" src="https://user-images.githubusercontent.com/49010201/183246427-8ee52979-7ee4-438a-92d1-cdb2b5062df0.png">

**Comment by YXL76** [comment]
打开`~/.cloudmusic/err-<version>.log`

**Comment by zhucj1981** [comment]
之前为了排查问题，把.cloudmusic清空了，重装插件后还是没有文件生成
<img width="175" alt="image" src="https://user-images.githubusercontent.com/49010201/183247425-04695351-e20e-431c-a2ba-ad0a559f81eb.png">

**Comment by YXL76** [comment]
你是不是没有打开队列的`TreeView`

**Comment by zhucj1981** [comment]
是的，打开就立马连上了。这也有关联？

**Comment by YXL76** [comment]
打开后拓展才会启动，或者在设置里勾选`AutoStart`

**Comment by zhucj1981** [comment]
好的，了解了，谢谢🙏
