### ISSUE TITLE
插件歌单和队列为空> >

### ISSUE THREAD

**Issue by 131460606** [YXL76/cloudmusic-vscode#787]
> > 
> 
> 什么列表

就是刚安装完插件，打开后歌单和队列空白

_Originally posted by @131460606 in https://github.com/YXL76/cloudmusic-vscode/issues/754#issuecomment-1214146933_

**Comment by YXL76** [comment]
**Error information**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`.
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容。

**Server logs**
Execute `cloudmusic.openLogFile`.
执行 `cloudmusic.openLogFile`。
