### ISSUE TITLE
8.7日更新后无法播放个人收藏的歌单

### ISSUE THREAD

**Issue by 3DMXM** [YXL76/cloudmusic-vscode#788]
点击个人收藏的歌单 播放提示 
```
运行命令 cloudmusic.playPlaylist 错误: 出现未知错误。有关详细信息，请参阅日志。。这可能是由提交 cloudmusic.playPlaylist 的扩展引起的。

```

播放其他歌曲没有这个问题

控制台截图

![image](https://user-images.githubusercontent.com/28587093/184780627-ba25693e-e37d-499c-84b7-b4461870b0d0.png)

**Comment by lvlouhs** [comment]
这个问题我也见过，播放整个歌单或者将整个歌单添加到播放列表时会出现，第一次操作时无反应，第二次操作出现图中报错通知，我是在第一次操作后展开歌单列表解决的

**Comment by YXL76** [comment]
> 这个问题我也见过，播放整个歌单或者将整个歌单添加到播放列表时会出现，第一次操作时无反应，第二次操作出现图中报错通知，我是在第一次操作后展开歌单列表解决的

见上一条评论

**Comment by YXL76** [comment]
已经说过了，等待 https://github.com/microsoft/vscode/issues/129019

**Comment by YXL76** [comment]
在`v9.14.0`修复
