### ISSUE TITLE
Visual Studio Code - Insiders 启动失败

### ISSUE THREAD

**Issue by zyd16888** [YXL76/cloudmusic-vscode#8]
版本信息如下：
Visual Studio Code - Insiders
Version: 1.48.0-insider (user setup)
Commit: Oa7364f00514c46cgcaceeceI 5eI f82f82e3712f
Date: 2020-07-22T05:49.27.463Z (18 hrs ago)
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 83.110.13-electron.0
OS: Windows NT x64 10.0.19041

报错信息如下：
![image](https://user-images.githubusercontent.com/26684563/88240997-74474580-ccbb-11ea-86fa-43a3aae5fc9f.png)

![image](https://user-images.githubusercontent.com/26684563/88241030-86c17f00-ccbb-11ea-89f3-1592019e20e7.png)

**Comment by YXL76** [comment]
请更新至`v3.2.2`，检查是否可以正常运行。 @zyd16888

**Comment by zyd16888** [comment]
Windows Sandbox 下测试依然无法正常运行
![image](https://user-images.githubusercontent.com/26684563/88350407-a45b1b00-cd85-11ea-906a-b55db4eacbeb.png)

但是在我主机上，更新到 `v3.2.2` 以后，已经可以正常使用
![image](https://user-images.githubusercontent.com/26684563/88350606-306d4280-cd86-11ea-9f92-f39bf409f887.png)

**Comment by YXL76** [comment]
关于在`sandbox`中无法运行，我确信是由于缺少所需的运行库，具体可以查看[electron#892](https://github.com/electron/electron/issues/892#issuecomment-66009910)，安装`Visual Studio C++ Redistributable`后应该就能运行本插件。

我后续可能会研究所需运行库的具体版本，现在认为此issue已结束。 @zyd16888
