### ISSUE TITLE
歌词

### ISSUE THREAD

**Issue by QHPHBias** [YXL76/cloudmusic-vscode#800]
![image](https://user-images.githubusercontent.com/37543914/188050794-38d1ccce-9915-4f26-a90b-bcf73eb3b75b.png)
![image](https://user-images.githubusercontent.com/37543914/188050871-83c5e5f4-d189-4af8-ac7b-534c96fc7e0c.png)

底部导航栏中没有歌词的显示，不管是本地歌曲还是在线歌曲。歌词显示开关已经打开了，但是没办法显示

**Comment by YXL76** [comment]
截图里是关闭的状态

**Comment by shanyan-wcx** [comment]
vscode更新到1.71.0后歌词没法显示了，在编辑器中显示也只会打开以前的歌词，而不是现在在播放的

**Comment by shanyan-wcx** [comment]
vscode更新到1.71.0后状态栏歌词没法显示了

**Comment by QHPHBias** [comment]
> 截图里是关闭的状态

你好，我这边打开了歌词显示（状态栏显示“禁用”），歌词一样不会显示。并且，在昨天更新到9.16.2版本后，不仅本地音乐，在线音乐都无法播放了，一直处于加载状态

**Comment by QHPHBias** [comment]
> > 截图里是关闭的状态
> 
> 你好，我这边打开了状态（栏显示“禁止显示”），歌词一样不会。并且，在昨天更新到 9.1.6.2 版本之后，本地音乐，在线播放都无法显示歌词了，一直保持加载状态

问题更新，在重启过一次电脑并将插件卸载重装后，在线音乐可以正常播放了，并且可以正常显示歌词，但是本地音乐依旧无法播放。（格式：.mp3）

**Comment by QHPHBias** [comment]
> > 截图里是关闭的状态
> 
> 你好，我这边打开了状态（栏显示“禁止显示”），歌词一样不会。并且，在昨天更新到 9.1.6.2 版本之后，本地音乐，在线播放都无法显示歌词了，一直保持加载状态

问题更新，在重启过一次电脑并将插件卸载重装后，在线音乐可以正常播放了，并且可以正常显示歌词，但是本地音乐依旧无法播放。（格式：.mp3）

**Comment by YXL76** [comment]
会显示在 Treeview 里吗？方便提供一个文件吗？

**Comment by QHPHBias** [comment]
Treeview 显示正常，但是播放状态显示一直加载。这边提供1个文件供您测试，并提供一个目录供您参考。
图片为文件目录下的文件分布情况。





qhph_Bias
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "YXL76/cloudmusic-vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 歌词 (Issue #800)





 
会显示在 Treeview 里吗？方便提供一个文件吗？

**Comment by QHPHBias** [comment]
qhph_Bias
***@***.***



&nbsp;

**Comment by YXL76** [comment]
emm 图片和文件都看不到

**Comment by QHPHBias** [comment]
这样可以么





qhph_Bias
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YXL76/cloudmusic-vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 中午11:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 歌词 (Issue #800)





 
emm 图片和文件都看不到

**Comment by YXL76** [comment]
不行

**Comment by QHPHBias** [comment]
> 不行

![image](https://user-images.githubusercontent.com/37543914/188529978-3abe3758-3e3c-4a86-beaf-62e1100890af.png)
我尝试这样给您发送问题，应该是可行的。当加载本地音乐时会一直处于加载状态。
![1662429022404](https://user-images.githubusercontent.com/37543914/188530231-e28cd740-77c3-415c-a31e-a2eb8508f880.jpg)
这个是我本地音乐的目录，其中音乐文件均为普通.mp3格式的文件，所有音乐均无法播放。

**Comment by YXL76** [comment]
请检查`v9.16.4`

**Comment by QHPHBias** [comment]
是邮箱的问题么？我刚刚想发3.74M的文件，但是大小超过限制了，会不会是附件信息被邮箱拦截了




qhph_Bias
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YXL76/cloudmusic-vscode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 歌词 (Issue #800)





 
不行
