### ISSUE TITLE
无法播放音乐

### ISSUE THREAD

**Issue by linyuansup** [YXL76/cloudmusic-vscode#815]
**Describe the bug**
清楚简明地描述了该错误是什么。

经常会无法播放本地和联网音乐，退出账号重新登录可解决

**Error information**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`.
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容。
无
**Server logs**
Execute `cloudmusic.openLogFile`.
执行 `cloudmusic.openLogFile`。
也无
**Environment**
Paste the content in `Help->About`.
粘贴`帮助->关于`中的内容。
![188672135-93f09c73-6739-4812-86d2-327cdc037d8f](https://user-images.githubusercontent.com/49548096/189473337-fa84f6e9-2533-4a6a-856d-12777ab062bf.png)

**Comment by henrytbtrue** [comment]
我也遇到了这个问题，退回到 9.15.x 版本才能解决

**Comment by YXL76** [comment]
把`cloudmusic.player.mode`设置成`native`吧

**Comment by AikiQuare** [comment]
同样遇到这样的问题，表现为一直在缓冲无法播放，在网易云app以及网页端中是正常的，排除网络问题

**Comment by YuLun-bili** [comment]
我把`player.mode`改`native`之后又重新登录就好使了

**Comment by lucaszhang99** [comment]
> 我也遇到了这个问题，退回到 9.15.x 版本才能解决

回退到9.15.1 后恢复正常

**Comment by YXL76** [comment]
> > 我也遇到了这个问题，退回到 9.15.x 版本才能解决
> 
> 回退到9.15.1 后恢复正常
> 

`9.16`所有版本都不行吗？

**Comment by yemaxul** [comment]
cloudmusic版本：v9.15.1

问题：
根据评论建议进行了降级，但问题无法解决。
当player：mod，设置为auto的时候可以登陆，但歌曲一直是加载中
当player：mod，设置为native，重载vscode后，登陆信息消失，且无法登陆，改回auto模式并重载vscode后显示登陆了，有歌单信息但是无法播放音乐，一直加载中。
感谢😘😚😗😙！

环境：
code-server: v4.8.3
版本: 1.72.1
提交: 129500ee4c8ab7263461ffe327268ba56b9f210d
日期: 2022-11-07T18:19:38.940Z
浏览器: Mozilla/5.0 (Linux; Android 11; 21051182C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 EdgA/106.0.1370.47

**Comment by lucaszhang99** [comment]
> > > 我也遇到了这个问题，退回到 9.15.x 版本才能解决
> > 
> > 
> > 回退到9.15.1 后恢复正常
> 
> `9.16`所有版本都不行吗？

今早打开后9.15.1也一直在loading 
![image](https://user-images.githubusercontent.com/48301313/202562558-acb583bc-99ea-4f36-9906-80e15d2a4ea2.png)

**Comment by lucaszhang99** [comment]
目前我的解决办法是如果打开后一直在loading的话重装任意版本后就行了
