### ISSUE TITLE
本地音乐列表消失问题

### ISSUE THREAD

**Issue by QHPHBias** [YXL76/cloudmusic-vscode#818]
![image](https://user-images.githubusercontent.com/37543914/189785569-923f0aa8-ab8e-4aba-8054-0e66a0ffedee.png)
您好，我在更新至9.16.7版本之后发现，没有本地音乐播放列表的显示了。不知是错误还是bug。

**Comment by YXL76** [comment]
右上角三个点

**Comment by QHPHBias** [comment]
![image](https://user-images.githubusercontent.com/37543914/189799986-fa0fd30c-1713-4f37-87fa-81dc71014a2c.png)
 好像并没有发现本地音乐播放列表的选项

**Comment by YXL76** [comment]
是不是被拖到其他地方去了？

**Comment by QHPHBias** [comment]
不，在上周五一切还是正常的，这期间我并未使用过VSCode。
我刚刚把扩展重装了一下，依旧没有发现本地音乐列表。

**Comment by YXL76** [comment]
那你先用老版本吧

**Comment by QHPHBias** [comment]
发现问题了，因为安装了另一款插件，那一款插件也有一个名叫“本地”的子模块，两个子模块冲突，云音乐的“本地”自动迁移过去了，也许是bug？
