### ISSUE TITLE
已经启用底栏歌词，但是不显示

### ISSUE THREAD

**Issue by moewang0321** [YXL76/cloudmusic-vscode#847]
底栏的歌词菜单中点击启用了，但还是没有歌词
![image](https://user-images.githubusercontent.com/48441577/200722826-5ac38d9e-4f4c-425a-ab6a-01facde6adbd.png)

**Comment by iwxyi** [comment]
我的也是这样，只有这一个歌词的按钮

**Comment by YXL76** [comment]
全部歌词里看到的歌词吗

**Comment by iwxyi** [comment]
看得到歌词，就是底栏不显示

兰陈昕 ***@***.***> 于 2022年12月26日周一 下午8:09写道：

**Comment by YXL76** [comment]
提供一个歌曲链接吧

**Comment by moewang0321** [comment]
> 

分享王以太/艾热 AIR的单曲《别怕变老》: https://y.music.163.com/m/song?id=1876179147&userid=284480881&dlt=0846 (来自@网易云音乐)

**Comment by iwxyi** [comment]
发现原因了，那个歌词的文字变成“禁用”的时候才是开启，还要等到切换下一行歌词的时候才会刷新

MoeWang ***@***.***> 于 2022年12月27日周二 上午7:59写道：

**Comment by moewang0321** [comment]
> 等到切换

我一直是禁用，但也没有

**Comment by YXL76** [comment]
试一试 `v9.18.0` 吧 @moewang0321

**Comment by moewang0321** [comment]
> 试一试 `v9.18.0` 吧 @moewang0321

嗯嗯9.18好用了！感谢
