### ISSUE TITLE
无法在搜索中正常输入，焦点会丢失

### ISSUE THREAD

**Issue by zhucj1981** [YXL76/cloudmusic-vscode#848]
**Describe the bug**
在搜索时，一两次按键后输入框的焦点就丢失。以前没出过这个问题

<img width="631" alt="image" src="https://user-images.githubusercontent.com/49010201/201563739-c6462099-722b-4d39-ab16-98f7771fb979.png">

<img width="618" alt="image" src="https://user-images.githubusercontent.com/49010201/201563864-975d104d-4f91-4d01-aba3-e1db10da3c32.png">

**Environment**
版本: 1.73.1 (Universal)
提交: 6261075646f055b99068d3688932416f2346dd3b
日期: 2022-11-09T02:08:38.961Z (5 天前)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
沙盒化: No。

macOS 12.6.1

**Comment by YXL76** [comment]
在 `v9.18.0` 中修复
