### ISSUE TITLE
About lyrics 关于歌词

### ISSUE THREAD

**Issue by KaSock** [YXL76/cloudmusic-vscode#855]
**Is your feature request related to a problem? Please describe.**
在日语英语的歌曲播放时，我需要去手动切换翻译模式，中文歌曲时，又得重新切换回原文

**Describe the solution you'd like**
想要在听固定语言时自动切换歌词显示模式

**Describe alternatives you've considered**
用户可以自选不同语言歌词的显示模式

**Additional context**
翻译模式下中文歌曲会不显示歌词
![image](https://user-images.githubusercontent.com/56071624/205484065-d7a1d5e9-7b87-44f0-ab48-4b411f2c4bf6.png)

**Comment by KaSock** [comment]
英文歌曲还好，日文德文那些就寄了

**Comment by YXL76** [comment]
`v9.18.0` 中会回退到原文

**Comment by KaSock** [comment]
> `v9.18.0` 中会回退到原文

感谢您的回应与维护😃
