### ISSUE TITLE
vscode更新1.74后无法播放

### ISSUE THREAD

**Issue by Gio-2020** [YXL76/cloudmusic-vscode#857]
vscode更新1.74后插件无法使用，重装插件后(v9.17.0)一直加载中，无法登录
![image](https://user-images.githubusercontent.com/65337741/206417365-ec4ff000-4b32-46a8-a7a4-e0ee800cf4db.png)
update:
成功登录，但依然不能播放
![image](https://user-images.githubusercontent.com/65337741/206419453-44f71a71-a91e-4174-8b36-3c4e805da3d2.png)

**Comment by YXL76** [comment]
`v9.17.1`有个临时的修复，要确保`cloudmusic.player.mode`设置为`auto`或`native`

**Comment by Vi-brance** [comment]
我在最新的版本中也遇到了这个问题，扩展一直卡在加载中的状态，不知道现在有没有解决办法？

**Comment by YXL76** [comment]
> 我在最新的版本中也遇到了这个问题，扩展一直卡在加载中的状态，不知道现在有没有解决办法？

大概率不是同个问题，提个新 issue 吧
