### ISSUE TITLE
使用的问题

### ISSUE THREAD

**Issue by QUAN-1** [YXL76/cloudmusic-vscode#86]
没有登录账号图标了怎么登陆

![image](https://user-images.githubusercontent.com/61101327/95569329-04459180-0a58-11eb-93b7-b6f6e4378069.png)
而且左边这个也是灰色的

![image](https://user-images.githubusercontent.com/61101327/95569457-30611280-0a58-11eb-98e8-3bc76db36b0c.png)
我第一次用的时候还好好

**Comment by YXL76** [comment]
`Activity bar`的帐号图标与本拓展无关，使用前要激活，还是说你禁用了插件。 @QUAN-1

**Comment by QUAN-1** [comment]
下载vs code之后一直这样的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YXL76/cloudmusic-vscode"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月9日(星期五) 晚上7:07
收件人:&nbsp;"YXL76/cloudmusic-vscode"<cloudmusic-vscode@noreply.github.com&gt;;
抄送:&nbsp;"QUAN-铨"<2395816280@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 使用的问题 (#86)





 
Activity bar的帐号图标与本拓展无关，使用前要激活，还是说你禁用了插件。 @QUAN-1

**Comment by YXL76** [comment]
我不明白你的问题，你能截个完整的图片吗？ @QUAN-1

**Comment by QUAN-1** [comment]
就是这样，没得图标，不知道怎么登录


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YXL76/cloudmusic-vscode"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月9日(星期五) 晚上10:34
收件人:&nbsp;"YXL76/cloudmusic-vscode"<cloudmusic-vscode@noreply.github.com&gt;;
抄送:&nbsp;"QUAN-铨"<2395816280@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 使用的问题 (#86)





 
我不明白你的问题，你能截个完整的图片吗？ @QUAN-1

**Comment by YXL76** [comment]
你没有这个图标吗？ @QUAN-1 
![Screenshot_20201009_225317](https://user-images.githubusercontent.com/43405544/95599284-75e70500-0a83-11eb-8676-722109586db4.png)

**Comment by QUAN-1** [comment]
没有，网上看的别人vs code的截图，也没有，一开始我都能用了的，更新版本后就没了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YXL76/cloudmusic-vscode"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月9日(星期五) 晚上11:02
收件人:&nbsp;"YXL76/cloudmusic-vscode"<cloudmusic-vscode@noreply.github.com&gt;;
抄送:&nbsp;"QUAN-铨"<2395816280@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 使用的问题 (#86)





 
你没有这个图标吗？ @QUAN-1

**Comment by YXL76** [comment]
你右键看看有没有我圈出来的这个选项。 @QUAN-1 
![Screenshot_20201009_230655](https://user-images.githubusercontent.com/43405544/95599948-556b7a80-0a84-11eb-9e2d-0ca3fb428b90.png)

**Comment by QUAN-1** [comment]
圈了，不然那个截图那里左边也不会出现那个图标吧------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;兰陈昕&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月9日(星期五) 晚上11:09
收件人:&nbsp;&quot;YXL76/cloudmusic-vscode&quot;<cloudmusic-vscode@noreply.github.com&gt;;
抄送:&nbsp;&quot;QUAN-1&quot;<2395816280@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 使用的问题 (#86)

**Comment by YXL76** [comment]
你给的截图中的那个图标和本拓展没有任何关系。 @QUAN-1

**Comment by YXL76** [comment]
你激活插件后执行`Cloudmusic: Sign in`，如果不能用请在`Help->Toggle Developer Tools->Console`中查看错误信息并发给我。 @QUAN-1

**Comment by QUAN-1** [comment]
我的…我明天试试，谢谢你------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;兰陈昕&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月9日(星期五) 晚上11:22
收件人:&nbsp;&quot;YXL76/cloudmusic-vscode&quot;<cloudmusic-vscode@noreply.github.com&gt;;
抄送:&nbsp;&quot;QUAN-1&quot;<2395816280@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 使用的问题 (#86)

**Comment by QUAN-1** [comment]
这样的

图标也有啊



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YXL76/cloudmusic-vscode"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月9日(星期五) 晚上11:22
收件人:&nbsp;"YXL76/cloudmusic-vscode"<cloudmusic-vscode@noreply.github.com&gt;;
抄送:&nbsp;"QUAN-铨"<2395816280@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 使用的问题 (#86)





 
你激活插件后执行Cloudmusic: Sign in，如果不能用请在Help-&gt;Toggle Developer Tools-&gt;Console中查看错误信息并发给我。 @QUAN-1

**Comment by YXL76** [comment]
我看不到你的图片。所以你执行了我的操作吗，有错误信息吗？@QUAN-1

**Comment by QUAN-1** [comment]
整个屏幕是这样的

然后，执行登录是这样的错误





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YXL76/cloudmusic-vscode"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月10日(星期六) 上午9:35
收件人:&nbsp;"YXL76/cloudmusic-vscode"<cloudmusic-vscode@noreply.github.com&gt;;
抄送:&nbsp;"QUAN-铨"<2395816280@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [YXL76/cloudmusic-vscode] 使用的问题 (#86)





 
我看不到你的图片。所以你执行了我的操作吗，有错误信息吗？@QUAN-1

**Comment by YXL76** [comment]
邮箱回复我看不到图片，你到github上发，或给个图床链接@QUAN-1

**Comment by QUAN-1** [comment]
![image](https://user-images.githubusercontent.com/61101327/95643047-1585b100-0adf-11eb-842c-9f097d4566f1.png)
![image](https://user-images.githubusercontent.com/61101327/95643063-29c9ae00-0adf-11eb-8b9a-70a749b84696.png)
这样的

**Comment by YXL76** [comment]
你没有激活插件，请你仔细看看使用说明 @QUAN-1

**Comment by QUAN-1** [comment]
![image](https://user-images.githubusercontent.com/61101327/95643141-c55b1e80-0adf-11eb-814c-94f9cd67bb30.png)
点击之后就是这样，怎么激活，
鼠标左键的话就是只能控制他的展开与折叠

**Comment by YXL76** [comment]
你尝试重装拓展或者安装之前的版本，看看是不是都不能用@QUAN-1

**Comment by QUAN-1** [comment]
都不行，算了吧，谢谢你了

**Comment by QUAN-1** [comment]
可能是我电脑有问题

**Comment by YXL76** [comment]
VS Code版本信息？ @QUAN-1

**Comment by QUAN-1** [comment]
![image](https://user-images.githubusercontent.com/61101327/95643577-972b0e00-0ae2-11eb-9972-a693d4d52439.png)
这是我的vs code

**Comment by b4imetu** [comment]
@QUAN-1 安装插件后使用快捷键 `Ctrl+Shift+P` 键入 `>Sign in` 看是否有执行 Cloudmusic登录 的选项

**Comment by QUAN-1** [comment]
![image](https://user-images.githubusercontent.com/61101327/95643612-d35e6e80-0ae2-11eb-9171-16fccc1b1e40.png)
有的，就是会报错

**Comment by YXL76** [comment]
你用的是win7吗？@QUAN-1

**Comment by QUAN-1** [comment]
嗯嗯
之前用起来过，现在不行了

**Comment by YXL76** [comment]
win7没有经过测试。如果有空我弄个虚拟机看看吧 @QUAN-1

**Comment by QUAN-1** [comment]
好，没办法了，这个东西真的挺方便的，哈哈，还是谢谢啦

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/97530635-8426a200-19ed-11eb-9f85-fe2ed665d0d4.png)
无限加载中，播放不了什么情况 
![image](https://user-images.githubusercontent.com/8703951/97530654-8e48a080-19ed-11eb-9f30-9d963400ffaa.png)

**Comment by YXL76** [comment]
网络问题？我这边可以正常使用 @531431988

**Comment by 531431988** [comment]
> 网络问题？我这边可以正常使用 @531431988

那我是怎么提的问题？应该是其他问题，有人遇到没

**Comment by StephenChyi** [comment]
总是登录失败
![image](https://user-images.githubusercontent.com/42527566/98086787-306afb80-1eba-11eb-8f3d-e34f40988c9f.png)
肯定账号密码正确

**Comment by b4imetu** [comment]
> 总是登录失败
> 肯定账号密码正确

我这里没问题，你应该贴一下VSCode版本信息才对 @StephenChyi

**Comment by StephenChyi** [comment]
> > 总是登录失败
> > 肯定账号密码正确
> 
> 我这里没问题，你应该贴一下VSCode版本信息才对 @StephenChyi
![image](https://user-images.githubusercontent.com/42527566/98089528-ce13fa00-1ebd-11eb-8e43-d040287372cf.png)

**Comment by StephenChyi** [comment]
> > 总是登录失败
> > 肯定账号密码正确
> 
> 我这里没问题，你应该贴一下VSCode版本信息才对 @StephenChyi

![image](https://user-images.githubusercontent.com/42527566/98089567-df5d0680-1ebd-11eb-9ab6-ad11c2d94275.png)

**Comment by StephenChyi** [comment]
> > 总是登录失败
> > 肯定账号密码正确
> 
> 我这里没问题，你应该贴一下VSCode版本信息才对 @StephenChyi

[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z (3 wks ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

[OK] [Copy]

**Comment by YXL76** [comment]
1. 你是使用邮箱还是手机登录？
2. 是否有使用代理软件？
@StephenChyi

**Comment by StephenChyi** [comment]
> 1. 你是使用邮箱还是手机登录？
> 2. 是否有使用代理软件？
>    @StephenChyi

手机和邮箱登录都不行，没有代理软件，网易云客户端就可以登录

**Comment by YXL76** [comment]
不知道你方不方便使用[NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)登录，好让我确定是不是上游的问题 @StephenChyi

**Comment by StephenChyi** [comment]
> 不知道你方不方便使用[NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)登录，好让我确定是不是上游的问题 @StephenChyi

试了api没问题，我今天又试着登录了下，瞬间可以了，这个是什么原因呀

**Comment by YXL76** [comment]
> > 不知道你方不方便使用[NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)登录，好让我确定是不是上游的问题 @StephenChyi
> 
> 试了api没问题，我今天又试着登录了下，瞬间可以了，这个是什么原因呀

不太懂，我之后应该加上显示错误信息的功能
