### ISSUE TITLE
command 'cloudmusic.addAccount' not found

### ISSUE THREAD

**Issue by hallelujahjeff** [YXL76/cloudmusic-vscode#882]
所有相关命令都报这个，卸载重装无效。另外由于vscode配了同步，其他电脑上的云音乐插件也报这个错误了。。
![image](https://user-images.githubusercontent.com/32906436/213379480-1ac986f1-9b1b-47ac-9608-6ac58374701a.png)

**Comment by YXL76** [comment]
无法复现，禁用其他插件之后呢
