### ISSUE TITLE
Windows 7,VSCode1.70.3,不能登陆

### ISSUE THREAD

**Issue by Lisu-Liso** [YXL76/cloudmusic-vscode#883]
**Describe the bug**
在登陆时随便点击一种登录方式，然后下面进度条会一直跑，不会进行下一步操作

**Error information**
![image](https://user-images.githubusercontent.com/99577760/213842880-2d4c63f8-01a0-4c37-9f61-c21e7f1402c6.png)

**Server logs**
日志太长了，超出字数6w+

**Environment**
版本: 1.70.3 (user setup)
提交: a21a160d630530476218b85db95b0fd2a8cd1230
日期: 2022-08-31T08:03:55.990Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by Lisu-Liso** [comment]
其他操作系统和电脑也不能用。

**Comment by Lisu-Liso** [comment]
OK我理解了。用VSC NeteaseMusic的替换脚本替换下（交互文档）就能用了。

**Comment by Lisu-Liso** [comment]
登陆上就又不能用了，重新装一下VSCode就好啦！

**Comment by Lisu-Liso** [comment]
好棒，但是我不知道为什么又坏了。

**Comment by YXL76** [comment]
win7应该不能运行，不把日志发出来我也不知道问题是什么

**Comment by Lisu-Liso** [comment]
我遇到这个问题的时候所有设备都不能正常工作

**Comment by Lisu-Liso** [comment]
2023-02-19T02:52:04.581Z Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\.cloudmusic\retain'
新机器日志。只有一行
