### ISSUE TITLE
如何显示歌词

### ISSUE THREAD

**Issue by BRabb1t** [YXL76/cloudmusic-vscode#9]

**Comment by YXL76** [comment]
`cloudmusic.toggleButton` @BRabb1t

**Comment by BRabb1t** [comment]
抱歉，刚接触vscode，能告诉具体的操作吗，谢谢

**Comment by YXL76** [comment]
按`Ctrl+Shift+P`打开`Command Palette`，然后输入`Cloudmusic: Toggle button`

**Comment by BRabb1t** [comment]
谢谢 :)

**Comment by nshusr** [comment]
不能默认就显示歌词么 😄

**Comment by YXL76** [comment]
> 不能默认就显示歌词么

#6

**Comment by RoderickQiu** [comment]
> 
> 
> > 不能默认就显示歌词么
> 
> #6

新用户发表下意见。
ToggleButton这一属性在文档里写的不明不白，没有直接写出可以用来隐藏或者显示歌词。
此外，个人觉得不显示歌词可能才是小众需求吧？
不过，最简单的改法其实就是把文档写的好一点，不来repo看一圈我还以为开发者是在唬人，其实没有显示歌词功能呢。来了repo才知道怎么搞。
