### ISSUE TITLE
[bug][显示问题]左侧显示栏有问题

### ISSUE THREAD

**Issue by TLLord** [YXL76/cloudmusic-vscode#917]
![image](https://user-images.githubusercontent.com/50732352/227979904-a3cd1d95-38e8-4939-9594-b17c79d503b7.png)
如图，下拉重叠了
版本	Windows 11 家庭中文版
版本	21H2
安装日期	‎2022/‎3/‎10
操作系统版本	22000.1696
Version: 1.76.2 (system setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

**Comment by YXL76** [comment]
https://github.com/YXL76/cloudmusic-vscode/issues/783
