### ISSUE TITLE
无法播放

### ISSUE THREAD

**Issue by htb8341** [YXL76/cloudmusic-vscode#919]
账号模块加载不出来，本地曲库和其他模块无法使用并弹出报错
报错弹窗如下：运行命令 cloudmusic.playLocalFile 错误: command 'cloudmusic.playLocalFile' not found。这可能是由提交 cloudmusic.playLocalFile 的扩展引起的。
希望大佬可以解决一下~

**Comment by YXL76** [comment]
**Error information**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`.
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容。

**Server logs**
Execute `cloudmusic.openLogFile`.
执行 `cloudmusic.openLogFile`。

**Environment**
Paste the content in `Help->About`.
粘贴`帮助->关于`中的内容。

**Comment by htb8341** [comment]
![Uploading question.png…]()

**Comment by htb8341** [comment]
<img width="1280" alt="question" src="https://user-images.githubusercontent.com/95856745/232308674-87842440-8f18-4ad4-8b0a-76a470dfe65b.png">
版本: 1.77.3
提交: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
日期: 2023-04-12T09:16:02.548Z
浏览器: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.77.3 Chrome/102.0.5005.196 Electron/19.1.11 Safari/537.36

那个serverlogs里的执行我没找到

**Comment by YXL76** [comment]
打开这个文件`%homepath%/.cloudmusic/err-<version>.log`

**Comment by htb8341** [comment]
2023-04-15T12:46:10.059Z Error
    at oa (file:///c:/Users/lenovo/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:36:3709)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-04-15T12:47:59.241Z Error
    at ea.Il [as _getPath] (file:///c:/Users/lenovo/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:36:3332)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ea.load (file:///c:/Users/lenovo/.vscode/extensions/yxl.cloudmusic-9.19.1-win32-x64/dist/server.mjs:35:11260)

**Comment by htb8341** [comment]
不用了大佬，卸载重装几次突然好使了，扫二维码重新登陆成功了，感谢

**Comment by htb8341** [comment]
在文件夹里打开vscode插件就不好使，把文件夹关闭就好了，可能是命令有什么冲突吧（悲）

**Comment by htb8341** [comment]
好像必须是不打开文件夹和状态下才能正常使用
<img width="1280" alt="微信截图_20230416204153" src="https://user-images.githubusercontent.com/95856745/232312225-d9630452-de8a-4960-a6d5-1cba7556d6fa.png">

**Comment by htb8341** [comment]
好像必须是不打开文件夹的状态下才能正常使用
<img width="1280" alt="微信截图_20230416204153" src="https://user-images.githubusercontent.com/95856745/232312312-de1c8cfb-5036-4fb0-a2bc-0ebad4a53168.png">

**Comment by YXL76** [comment]
好像不能复现

**Comment by MarlonTao1** [comment]
unable to verify the first certificate
 log里面提示的错误。
 登录不了，也用不了

**Comment by YXL76** [comment]
>  unable to verify the first certificate
>  log里面提示的错误。
>  登录不了，也用不了

网络问题

**Comment by Vi-brance** [comment]
我也遇到了这个问题，在 #921 中提到了，其中开发者工具没有任何报错信息，账号菜单始终处于加载状态，扩展相关的命令没有被注册，如果启动前清理了`.cloudmusic`文件夹则此文件夹仅被创建为空文件夹。

后来解决方式是展开了`队列`菜单（我之前用的时候默认折叠），只有展开此菜单有效，与其他菜单是否展开没有关系（初步排查结果），当此菜单展开时无论是否打开了文件夹项目都能正常加载扩展。

希望这些信息对你修复此bug有用 @YXL76 😊

**Comment by YXL76** [comment]
> 我也遇到了这个问题，在 #921 中提到了，其中开发者工具没有任何报错信息，账号菜单始终处于加载状态，扩展相关的命令没有被注册，如果启动前清理了`.cloudmusic`文件夹则此文件夹仅被创建为空文件夹。
> 
> 后来解决方式是展开了`队列`菜单（我之前用的时候默认折叠），只有展开此菜单有效，与其他菜单是否展开没有关系（初步排查结果），当此菜单展开时无论是否打开了文件夹项目都能正常加载扩展。
> 
> 希望这些信息对你修复此bug有用 @YXL76 😊

符合设计，需要补充文档
