### ISSUE TITLE
希望能在蓝牙耳机断开连接并再次连入后能继续播放

### ISSUE THREAD

**Issue by ws2bhhh** [YXL76/cloudmusic-vscode#920]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
清楚简洁地说明问题所在。例如，当[...]时，我总是感到沮丧。
类似#863。不过目前版本的插件可以在音量合成器内看到VSCode存在。
在蓝牙耳机断开连接再连入后无法继续播放，退出VSCode再打开依然无法播放。需要手动taskkill掉code.exe再打开VSCode才能恢复正常。

**Describe the solution you'd like**
简洁明了地描述您想要的功能。
希望再未来版本能在蓝牙耳机断开连接后再次连入后仍然能正常播放。

**Describe alternatives you've considered**
对您考虑过的所有解决方案或功能的简洁明了的描述。
手动taskkill掉code.exe再打开VSCode恢复正常。

**Additional context**
在此处添加有关功能请求的其他任何内容或屏幕截图。
似乎插件还影响到了VSCode的正常退出，无论是正常情况下的未断开耳机连接直接关闭窗口还是上述情景下都会有code.exe进程残留。这是正常情况吗？

**Comment by YXL76** [comment]
为了`reload`后能够继续播放，插件会延迟40s退出
