### ISSUE TITLE
声音无法从有线耳机播放

### ISSUE THREAD

**Issue by guohaomeng** [YXL76/cloudmusic-vscode#923]
**声音无法从有线耳机播放**

当电脑插入有线耳机的时候，声音还是会从电脑自带喇叭播放，耳机里却没有声音。只有vscode里播放音乐时会出现这种情况，网页看视频或者用其他播放器听音乐声音就是正常从耳机播放

在音量合成器里怎么调都没用，很奇怪，不知道有没有碰到过这个问题的小伙伴，该咋解决

![屏幕截图(19)](https://user-images.githubusercontent.com/44870854/236657543-d821224e-b82d-48b8-9bef-a1af882414a5.png)

**Error information**

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/44870854/236657294-5c2aadda-9c85-4c89-9964-527b8bed8b00.png">

**Server logs**

```log
2023-05-07T03:40:56.444Z Error: ENOENT: no such file or directory, open 'C:\Users\meng\.cloudmusic\retain'
```

**Environment**

```
版本: 1.78.0 (user setup)
提交: 252e5463d60e63238250799aef7375787f68b4ee
日期: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
沙盒化: No
```

**Comment by Alin2077** [comment]
我遇到了同样的问题。老哥解决了吗？

**Comment by guohaomeng** [comment]
> 我遇到了同样的问题。老哥解决了吗？

没有😂，我发现插着耳机注销后再打开就能通过耳机播放了，但切换不了喇叭，他这个貌似只能固定一种方式播放，要么是耳机要么是喇叭，现在没法改

**Comment by youlan2333** [comment]
加一，我是无线耳机没声音，但是同样是用扩展实现的MP4视频播放就有声音

**Comment by Fuahi** [comment]
我也遇到了这个问题，我发现：如果我电脑是在连接蓝牙音频的情况下安装这个插件，那这个插件就只能通过蓝牙音频输出，切换到系统音频无声音；反之，如果是系统有线耳机输出的情况下安装这个插件，那就只能在有线耳机听到音乐，蓝牙耳机听不到。

**Comment by lutyne** [comment]
错误日志里显示无法找到播放设备，因为已被拔出， 常见到蓝牙耳机， 充个电回来已经无法播放了， 最新版有这个情况， 楼上说的7.7.2也有点， 但只要切个歌就回来了， 新版反而不行。

**Comment by cary-hu** [comment]
+1 蓝牙耳机播放没得声音，电脑音响有声音，log 文件：
![image](https://github.com/YXL76/cloudmusic-vscode/assets/41052104/41bf969b-678a-4d16-9cba-1fef5ee7f431)

**Comment by PLASTA0728** [comment]
我也遇见了这样的情况，而且很奇怪的是出问题之后第一次重装改回了外放，但是后来的重装也改不了有线耳机播放 而且有线耳机如果重接是哪里都播放不出来。
