### ISSUE TITLE
新版的无法登录，7.*版本的可以登录

### ISSUE THREAD

**Issue by 17764591637** [YXL76/cloudmusic-vscode#924]
**Describe the problem you encountered.**
A clear and concise description of what the question is.
清楚简洁地说明问题。

新版的无法登录，四种登录方式都不可以，要么显示登录失败，要么没反应，7.*版本的可以登录。

**Error information**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`.
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容。

**Server logs**
Execute `cloudmusic.openLogFile`.
执行 `cloudmusic.openLogFile`。

**Environment**
Paste the content in `Help->About`.
粘贴`帮助->关于`中的内容。
![image](https://github.com/YXL76/cloudmusic-vscode/assets/38268685/29a949f8-f175-4fee-a7e9-06455dfab4e5)

**Comment by 17764591637** [comment]
![Uploading image.png…]()

**Comment by YXL76** [comment]
> ![Uploading image.png…]()
> 

图片没传成功

**Comment by 17764591637** [comment]
> 

想给你看看日志的，但是那个log路径下没有报错的日志文件，旧版能用先用着吧。
新版账号密码登录一段时间后会弹出登录失败，
二维码登录不弹出二维码
手机验证码登录没收到验证码
