### ISSUE TITLE
请问下怎么搜索歌曲，找了好久没找到

### ISSUE THREAD

**Issue by sxk1305571399** [YXL76/cloudmusic-vscode#925]
**Describe the problem you encountered.**
A clear and concise description of what the question is.
清楚简洁地说明问题。

**Error information**
Paste or screenshot the content in `Help->Toggle Developer Tools->Console`.
粘贴或截屏`帮助->切换开发者工具->控制台`中的内容。

**Server logs**
Execute `cloudmusic.openLogFile`.
执行 `cloudmusic.openLogFile`。

**Environment**
Paste the content in `Help->About`.
粘贴`帮助->关于`中的内容。

**Comment by YXL76** [comment]
#644
