### ISSUE TITLE
启动cloudmusic之后, gitgraph 在status bar中消失了.

### ISSUE THREAD

**Issue by chaleaoch** [YXL76/cloudmusic-vscode#953]
vscode statusbar 默认如下图
![image](https://github.com/YXL76/cloudmusic-vscode/assets/11831441/776e7c53-e80a-447a-8734-1ad69ea029ef)
鼠标右键
![image](https://github.com/YXL76/cloudmusic-vscode/assets/11831441/2915e86f-8201-4786-b568-bc0025c88d67)
启动cloudmusic之后
gitgraph从statusbar消失了. 鼠标右键status bar 也看不见git graph选项了.
但是用命令 ctrl+shift+p 可以手动打开git graph view.

**Comment by YXL76** [comment]
无法复现

**Comment by chaleaoch** [comment]
我上传一个gif 供参考!
![1](https://github.com/YXL76/cloudmusic-vscode/assets/11831441/4566e251-e968-4bdd-ab15-514426c019b4)

**Comment by YXL76** [comment]
可能与远程环境有关 https://github.com/microsoft/vscode/issues/201795
