### ISSUE TITLE
播放音乐卡顿

### ISSUE THREAD

**Issue by g1fts** [YXL76/cloudmusic-vscode#966]
游戏里传送，音乐会有卡顿感，但是看了下任务管理器，CPU和内存都没有满载。

**Comment by g1fts** [comment]
> 尝试在任务管理器中调高优先级

![image](https://github.com/YXL76/cloudmusic-vscode/assets/20061353/cacc067d-17ff-4366-b38d-3213c9f4c80c)
额 哪个是？

**Comment by saltedfish2** [comment]
你可以开着资源管理器再打开vscode，点开歌曲的时候看一下哪个进程占用更多的cpu，再转到详细信息中调高优先级。

**Comment by g1fts** [comment]
> 你可以开着资源管理器再打开vscode，点开歌曲的时候看一下哪个进程占用更多的cpu，再转到详细信息中调高优先级。

.... n半年了啊，还挖坟.。。
